### PR TITLE
Convert offsetHeight/Width to clientHeight/Width

### LINKED ISSUE #6848: consider replacing offset{Height/Width} with client{Height/Width} for map canvas sizing
We currently use the map `container`'s `offsetHeight` and `offsetWidth` to size the map canvas element, which leads to odd behavior when using a border, including `Map#getCenter`, `Map#getBounds`, etc. returning incorrect values for what is visible to the user because some of the map canvas will be hidden by the container.

https://github.com/mapbox/mapbox-gl-js/blob/bf88cd735b06eacc607c188a2508c9912140768d/src/ui/map.js#L1474-L1477

image

image

If we used `clientHeight`/`clientWidth` to size the canvas, we would eliminate this behavior, but I'm not sure what the original reasoning was behind the choice to use `offset*`

This would qualify as a breaking change. If we decide not to make this change, we could specify in the documentation that a map's `container` cannot have a border. 

### Expected Behavior
with `client{Height/Width}` sizing, canvas remains within the main content area of the container element

expected

### Actual Behavior

with current behavior, canvas overflows the main content area and is partially hidden due to a border being used on the container element

actual

cc @mourner @jfirebaugh @kkaefer

### PR DESCRIPTION
**Pull request by ryanhamley**
## Launch Checklist

 - [x] briefly describe the changes in this PR
    - Converts `offset{Height/Width}` to `client{Height/Width}`
    - Fixes #6848  
 - [x] manually test the debug page

`master with offset{Height/Width}`
> screen shot 2018-08-14 at 1 16 23 pm

`canvas-hw with client{Height/Width}`
> screen shot 2018-08-14 at 1 17 08 pm

### CODE REVIEW

File: src/ui/popup.js [hunk 1]
```diff
@@ -290,8 +290,8 @@ export default class Popup extends Evented {
         const offset = normalizeOffset(this.options.offset);
 
         if (!anchor) {
-            const width = this._container.offsetWidth;
-            const height = this._container.offsetHeight;
+            const width = this._container.clientWidth;
+            const height = this._container.clientHeight;
```
Comment (mourner) [inline src/ui/popup.js]: This is measuring the popup's container rather than the map one, and we might want to leave `offset` sizes here, since for positioning the popup, it's important to take the whole popup into account (including borders/etc) rather than just its internal area.

Comment (ryanhamley) [reply src/ui/popup.js]: I reverted popups and the attribution and logo controls to use offsetWidth/Height
