### PR TITLE
An option to use a feature property as ID for feature state

### LINKED ISSUE #6019: RFC: Feature identity for interactivity
## Motivation

Vector tile sources split features across multiple tiles.

How do we tell if two features in different tiles are actually the same feature?
How do we highlight a feature across tile boundaries?
How do we only dispatch a feature event listener once, not once-per-tile?

We need some concept of what makes things "the same feature".

*For GeoJSON sources we have access to whole features so we can assign them ids guaranteed to be unique.*

### Option 1: do nothing

Treat vector tile features from different tiles as different features (like we do currently).

### Option 2: use the `id` field

Vector tile sources support an `id` field for features that [*SHOULD* be unique](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#42-features). We could treat all features with the same `id` as the same feature. Users would need to provide this in order for interactivity to work well.

It could be possible to have multiple features with the same `id` but different `properties`, which could create some weird edge cases. How would a theoretical `map.getFeatureProperties(sourceID, featureID)` handle this case?

Would features with missing `id` fields get merged into one feature? Or never get merged?

### Option 3: use the combination of the `id` field and `properties`

We could adapt the previous option and use the combination of the `id` and `properties` as a unique identifier. Features with the same `id` but different `properties` would be treated as different features. The nice thing about this is that a combined feature always has a well-defined `properties`. Also, merging could mostly work in many cases even if `id` is not provided.

### Option 4: Using a user defined function

We could extend the style spec to let users specify an expression to calculate a unique id. This expression could default to `["id"]`. This would provide a way to merge features together but it would also add extra complexity to the style spec.

This would have the same problem as Option 2, where a single combined feature could have multiple different `properties` objects.

Also, would this apply to just vector tile sources, or also geojson?

## Design

I think we should implement *Option 3*.
*Option 2* could be fine too.

Advantages of Option 3 over Option 2:
- the combined feature has a well-defined set of `properties`
- features without `id`s don't get merged into one giant feature

Disadvantages of Option 3 compared to Option 2:
- calculating the id could be more expensive since it has to process all the `properties`
- 3 could be harder to explain than option 2

Option 4 provides extra power but also extra complexity. I think that users that need this could implement it with event listeners and data joining.

#### vector tiles
```
TileA contains: [ { id: 123, type: 'multipoint', coords: [[10, 20]], properties: { key: value }]
TileB contains: [ { id: 123, type: 'multipoint', coords: [[40, 30]], properties: { key: value }]

mouseover the feature in TileA
both the feature in TileA and in TileB get highlighted
```

#### geojson
```
Source contains [{
    id: 123,
    geometry: { type: 'Point', coordinates: [10, 20] },
    properties: { key: 'value' }
}, {
    id: 123,
    geometry: { type: 'Point', coordinates: [40, 30] },
    properties: { key: 'value' }
}

mouseover the first feature
only the first feature gets highlighted
```

### Concepts

Hopefully this should be mostly intuitive. Users encountering unexpected behavior for vector tile interaction could be told to add a unique `id` to each of their features.

@kkaefer @asheemmamoowala @mollymerp @anandthakker @mourner @lucaswoj

### PR DESCRIPTION
**Pull request by mourner**
Closes #6019. An alternative proposal to #8448. Adds a source option to promote a specific property (either number or string) to `feature.id` for feature state, removing any limits on what type of values you can use (strings, floats, booleans, etc.):

```js
map.addSource('counties', {
    "type": "vector",
    "url": "mapbox://mapbox.82pkq93d",
    "promoteId": {"original": "COUNTY"}
});
...
map.setFeatureState({
    source: 'counties', 
    sourceLayer: 'original', 
    id: 'Marin County' // reference a feature by a county name for feature-state
}, {hover: true});
```

You can see how this works in the new `featurestate.html` debug page. Compared to #8448:

- You can use meaningful keys with feature state set/remove/get methods, making the API easier to use.
- Hides string to number hashing as an internal detail.

### TODO

- [x] Fix Flow errors
- [x] Extend to GeoJSON sources
- [x] Update unit tests 
- [x] Add spec docs

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] write tests for all new functionality
 - [x] document any changes to public APIs
 - [x] manually test the debug page
 - [ ] tagged `@mapbox/studio` and/or `@mapbox/maps-design` if this PR includes style spec or visual changes
 - [x] tagged `@mapbox/gl-native` if this PR includes shader changes or needs a native port

### CODE REVIEW

**Comment by mourner** [comment]
@asheemmamoowala good points!

> Your change breaks that by requiring the feature object to be modified so that id points to the `feature-state`-specific id instead.

Thinking more about it, should we consider overriding the feature object's `id`?  I can't think of a use case where it would be useful to keep the original feature `id` while opting to use a property for identification instead. Then we could rename the option to `promoteId` to make that override explicit.

It's also technically not a breaking change because the override only happens when you use that option, and if you do, passing the feature object to `setFeatureState` still works (even if the `id` is replaced). It will also be relatively easy to explain how this works in the docs.

In comparison, the option of having different code paths that treat `feature.id` differently depending on whether you also supply `properties` may be quite confusing for users.

Using an additional `featureStateID` property avoids the override, but also increases the API complexity, so is more prone to errors, and it will be more verbose.

**Comment by asheemmamoowala** [comment]
> should we consider overriding the feature object's `id`? I can't think of a use case where it would be useful to keep the original feature id while opting to use a property for identification instead.

That works! This would prevent you from applying feature-state to an entire class of features - but that is not the intent of these APIs and can be done with data-driven styling already.

Developers will want to work with the `id` in it's original form. How would you propose `promoteId` would work in that case? Specifically - will the promoted property value or its hash be used/exposed in
- the `id` of features returned from `qRF`
- the input to `Map#(set/get/remove)FeatureState` methods

**Comment by ryanbaumann** [comment]
cc/ @sansumbrella @jbranigan @cmtoomey

**Comment by mourner** [comment]
> This would prevent you from applying feature-state to an entire class of features

Technically it doesn't prevent anything — feature `id` doesn't have to be unique. E.g. see the county example I committed in the PR — it highlights multiple counties with the same name.

> Developers will want to work with the `id` in it's original form. How would you propose `promoteId` would work in that case? Specifically - will the promoted property value or its hash be used/exposed in
> 
> * the `id` of features returned from `qRF`
> * the input to `Map#(set/get/remove)FeatureState` methods

`feature.id` of features returned from `qRF` will have the promoted value (e.g. a string property). `set/get/removeFeatureState` will work with `id` in the form of that promoted value. The main difference of this PR and #8448 is that here, the derived integer value is never exposed publicly — it's an internal implementation detail of `FeaturePositionMap` only used for hashing keys, similar to how v8 internally implements object lookup by key.

**Comment by asheemmamoowala** [comment]
> see the county example I committed in the PR — it highlights multiple counties with the same name.

👍 

> feature.id of features returned from qRF will have the promoted value (e.g. a string property). set/get/removeFeatureState will work with id in the form of that promoted value.

👍

File: src/data/feature_index.js [hunk 1]
```diff
@@ -146,12 +146,12 @@ class FeatureIndex {
...
                 params.layers,
                 styleLayers,
-                (feature: VectorTileFeature, styleLayer: StyleLayer) => {
+                (feature: VectorTileFeature, styleLayer: StyleLayer, id: ?string | number) => {
                     if (!featureGeometry) {
                         featureGeometry = loadGeometry(feature);
                     }
                     let featureState = {};
-                    if (feature.id) {
+                    if (id) {
```
Comment (ansis) [inline src/data/feature_index.js]: Should this be `id !== undefined` to handle 0? (this would have been a pre-existing bug)

File: src/data/feature_index.js [hunk 2]
```diff
@@ -247,6 +249,16 @@ class FeatureIndex {
 
         return false;
     }
+
+    getId(feature: VectorTileFeature, sourceLayerId: string): string | number | void {
+        let id = feature.id;
+        if (this.promoteId) {
+            const propName = typeof this.promoteId === 'string' ? this.promoteId : this.promoteId[sourceLayerId];
```
Comment (ansis) [inline src/data/feature_index.js]: Is the intention to allow a single string that is used as the promoteId for all source-layers?

File: src/data/feature_position_map.js [hunk 3]
```diff
@@ -79,6 +82,14 @@ export default class FeaturePositionMap {
     }
 }
 
+export function getNumericId(value: mixed) {
+    const numValue = +value;
```
Comment (ansis) [inline src/data/feature_position_map.js]: I think this incorrectly handles strings that can be converted to javascript numbers but not javascript integers:
- integers javascript can't safely represent `'9007199254740993'`
- decimals `'1.2'`
- `'Infinity'`

It also looks like users of this function expect integers but this can return a float if given a float. Is that ok because it should never be given a float?

File: src/data/feature_index.js (hunk 1 above)
Comment (mourner) [reply src/data/feature_index.js]: Good catch, will fix!

File: src/data/feature_index.js (hunk 2 above)
Comment (mourner) [reply src/data/feature_index.js]: Yes — for better ergonomics if all source layers share the same unique property (which can often be the case), and also to better support GeoJSON sources (no need to set `{_geojsonTileLayer: '...'}`).

File: src/data/feature_position_map.js (hunk 3 above)
Comment (mourner) [reply src/data/feature_position_map.js]: Initially this was hashing all non-integer ids, but then I changed it because I thought there's no longer a need to have it limited to integer — those get saved in a Float64Array anyway, which supports decimals, values like `Infinity`, and values bigger than `MAX_SAFE_INTEGER`.

Comment (mourner) [reply src/data/feature_position_map.js]: > It also looks like users of this function expect integers 

Oh, actually, in addition to the above, this function being exported is a leftover from earlier — how things get stored in the position map should be an internal detail so there won't be "users" of this. I'll remove the "export".

Comment (ansis) [reply src/data/feature_position_map.js]: > those get saved in a Float64Array anyway, which supports decimals, values like Infinity, and values bigger than MAX_SAFE_INTEGER

Neither javascript numbers (which are 64 bit floats) or Float64Array can store integers > MAX_SAFE_INTEGER safely. Both `'9007199254740993'` and `'9007199254740992'` will look like the same id to this implementation. This might seem unlikely but we ran into this with iD editor because osm uses sequential 64 integers as ids.

Similar problems theoretically exist with decimals but seem less likely.

Comment (mourner) [reply src/data/feature_position_map.js]: Fair enough — updated to hash as a string in case a numeric id is more than `MAX_SAFE_INTEGER`.

**Comment by mourner** [comment]
cc @mapbox/gl-native — this would likely need to be included in the feature-state port work.

**Comment by waissbluth** [comment]
has this made it to a release? thank you

**Comment by mourner** [comment]
@waissbluth no, but it will get into the next release which is a few weeks away.

**Comment by Eh2406** [comment]
Looks like the documentation did not get updated to have this change `Features are identified by their id attribute, which must be an integer or a string that can be cast to an integer.` https://docs.mapbox.com/mapbox-gl-js/api/?size=n_10_n#map#setfeaturestate
