### PR TITLE
Clear tiles with zoom dependent `line-width` layers from the terrain render cache

### LINKED ISSUE #11956: Blur on traped lines inconsistent depending on zoom direction
From https://github.com/mapbox/mapbox-gl-js/pull/11951#issuecomment-1144637240:

> I also noticed an existing "bug" that is more visible now that the reference scale is higher than previously. Draped lines are more blurred around ~1.99 zoom level when approaching from a lower zoom level (e.g. zooming from 0 to 1.99) compared to zooming out (e.g. zooming out from 3 to 1.99). 
> 
> After a quick investigation I believe this is caused by the function `getPixelsToTileUnitsMatrix` using `transform.zoom` for computing the scale which shouldn't be done in draped rendering. While draping the zoom value is either ~1 or ~1.99 depending on direction of the zoom leading to this kind of blurriness. Fixed tile zoom level should be used instead. cc @karimnaaji.
> 
> https://user-images.githubusercontent.com/55925868/171596477-5801fd24-059e-4fd7-a490-7c8a49a23205.mp4

@mpulkki-mapbox I'm not able to reproduce this issue, maybe it's OS specific?

Trying the approach of fixed tile zoom:
```js
const s = scale * EXTENT / (tile.tileSize * Math.pow(2, tile.tileID.overscaledZ));
```
Lines become sharper, but we also introduce a sudden jump at each zoom level transition.

https://user-images.githubusercontent.com/14878684/171913001-803916d0-3301-46a4-841c-8bdf745bf25c.mov

cc @karimnaaji

### PR DESCRIPTION
**Pull request by stepankuzmin**
GL JS is not considering a line width change as a prerequisite to clear off tiles from the terrain render cache. Because of that, while zooming between two zoom levels, GL JS is using a stale zoom in `getPixelsToTileUnitsMatrix` during the entire range [z..z+1].

This fix clears tiles with zoom-dependent `line-width` layers from the terrain render cache. One thing that bugs me is that most Mapbox core styles use a composite source with zoom-dependant line layers. So we are basically disabling the terrain render cache for the composite source in core styles here.

Closes #11956

## Benchmarks

After running benchmarks comparing the main branch with this PR, there is a regression in `frameTimeAverage` and `percentDroppedFrames`, see:

* `streets-v11` https://sites.mapbox.com/benchmap-js-results/runs/1266
* `streets-v12` https://sites.mapbox.com/benchmap-js-results/runs/1267

## Before

https://user-images.githubusercontent.com/533564/211821451-c2b160b3-8f2b-47eb-a3d1-7c9f79025791.mov

## After

https://user-images.githubusercontent.com/533564/211821488-1ad97314-0979-4f28-9642-358e00fb2de0.mov

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] include before/after visuals or gifs if this PR includes visual changes
 - [x] post benchmark scores
 - [x] manually test the debug page
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [x] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog>fix blur on draped lines while zoom-in</changelog>`

### CODE REVIEW

**Review by karimnaaji — COMMENTED** [review]
The change looks good in itself, like you mentioned it's a bit worrisome to regress on performance with that change, putting the links to the benchmarks of the style for reference:

- streets-v11 https://sites.mapbox.com/benchmap-js-results/runs/1266

rendering-3d
Screen Shot 2023-01-20 at 11 53 23 AM
rendering-globe
Screen Shot 2023-01-20 at 11 53 31 AM

- streets-v12 https://sites.mapbox.com/benchmap-js-results/runs/1267

Screen Shot 2023-01-20 at 11 54 51 AM

Before going forward with this change, is there any alternative approach we could think about? For example, only trigger the render cache reload on larger/visible line-width differences (e.g. > 1/2px) in order to try and retain performance while still giving accurate results.

Otherwise, we should probably prefer the accuracy of the result and optimize this in the style itself.

**Comment by karimnaaji** [comment]
>@karimnaaji I've tried an approach that @mourner suggested — to clear terrain render cache on map moveend. The line issue is still visible while the map is moving, but after the move ends, it clears the render cache, and lines are refined.

Yes that's a good idea and seems like a good compromise, the benchmarks look good now 👍

File: src/terrain/terrain.js [hunk 1]
```diff
@@ -938,40 +944,69 @@ export class Terrain extends Elevation {
...
+            if (isHidden) continue;
+
+            if (layer.type === 'line') {
+                clearSourceCaches[sourceCache.id] = true;
+                const lineLayer = ((layer: any): LineStyleLayer);
+                this._clearLineLayerFromRenderCache(lineLayer, sourceCache);
+            } else if (layer.type === 'raster') {
+                clearSourceCaches[sourceCache.id] = true;
+                const rasterLayer = ((layer: any): RasterStyleLayer);
+                this._clearRasterLayerFromRenderCache(rasterLayer, sourceCache);
```
Comment (karimnaaji) [inline src/terrain/terrain.js:974]: Should clearing tiles that are faded raster still be running on every frame? It makes sense to adopt a less frequent clear for line-widths as it's a small noticeable difference, but not clearing fading rasters might lead to flickering. 

Could you confirm with a satellite style with a long added [raster-fade-duration](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#paint-raster-raster-fade-duration) to confirm that we're still ok on that?

Comment (stepankuzmin) [reply src/terrain/terrain.js]: @karimnaaji I've separated the function that clears fading raster tiles, so it's now called on every frame as before.

**Review by karimnaaji — APPROVED** [review]
:+1: Fix looks good to me

**Comment by stepankuzmin** [comment]
Note: I've tried to cover the issue in the render test but couldn't reproduce it
<details>
<summary><b>test case</b></summary>

```json
{
  "version": 8,
  "metadata": {
    "test": {
      "operations": [
        ["setProjection", "globe"],
        ["wait"],
        ["zoomTo", 2.9, {"duration": 2000}],
        ["wait"]
      ]
    }
  },
  "center": [0, 0],
  "zoom": 2.0,
  "pitch": 0,
  "bearing": 0,
  "sources": {
    "geojson": {
      "type": "geojson",
      "data": {
        "type": "MultiLineString",
        "coordinates": [
          [
            [
              0,
              20
            ],
            [
              20,
              0
            ],
            [
              0,
              -20
            ],
            [
              -20,
              0
            ],
            [
              0,
              20
            ]
          ]
        ]
      }
    }
  },
  "layers": [
    {
      "id": "background",
      "type": "background",
      "paint": {
        "background-color": "white"
      }
    },
    {
      "id": "line",
      "type": "line",
      "source": "geojson",
      "paint": {
        "line-width": 10,
        "line-opacity": 1
      }
    }
  ]
}

```

</details>
