### PR TITLE
Fix clearing tiles when using setStyle to switch projections

### LINKED ISSUE #12048: Raster layer displace on projection setStyle change
For a style with globe projection and raster imagery layer: Calling `setStyle` on that same style with a different projection then back to globe results in displaced raster tiles:

raster

---

**Version**: `2.9.1`
**Example**:  https://jsfiddle.net/tristen/ajvud3s7/

### PR DESCRIPTION
**Pull request by avpeery**
Fixes #12048. Toggling `setStyle` with globe projection and raster with another non-mercator projection caused displaced raster tiles. To clarify, this issue did not occur with toggling globe with vector tiles, or toggling globe with mercator. This issue also did not occur with using `setProjection`. 

The displacement of tiles is specific to toggling `setStyle` with `globe` and raster against a non-mercator projection.

The displacement of tiles was occurring because the `setStyle` flow had already updated `this.map.getProjection()` by the time it was called to set the prevProjection (see: [map.js#L1192](https://github.com/mapbox/mapbox-gl-js/blob/main/src/ui/map.js#L1192)). Since the `prevProjection` was the current projection in `setStyle` use-cases, `clearBackgroundTiles` was not called since it passed through line [map.js#L1219](https://github.com/mapbox/mapbox-gl-js/blob/main/src/ui/map.js#L1219).

This update sets `prevProjection` earlier for setStyle, initial style load, and setProjection allowing correct calls to `clearBackgroundTiles`.

**Before:**

https://user-images.githubusercontent.com/42715836/176597145-e2fb5268-d89c-4028-9587-e9d51171e183.mov

https://user-images.githubusercontent.com/42715836/176597168-a2bb76a4-880a-4526-816a-6fd33178c936.mov

**After:**

https://user-images.githubusercontent.com/42715836/176597398-fdba294a-9b49-43a0-8ccb-7d75840eebca.mov

https://user-images.githubusercontent.com/42715836/176597406-3566cc23-b8fa-48ec-beea-f20723a24918.mov

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] include before/after visuals or gifs if this PR includes visual changes
 - [x] write tests for all new functionality
 - [x] manually test the debug page
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [x] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog>Fix clearing raster tiles when toggling "setStyle" with a globe projection</changelog>`

### CODE REVIEW

**Review by SnailBones — CHANGES_REQUESTED** [review]
~I'm still seeing this issue the first time I switch to `globe` after loading the map in `albers`.~
Nevermind, it's working now! Nice work Anna!

An untested idea: what if instead of updating `_prevProjection` in `style.js`, it was updated at the end of `map._updateProjection`?

**Review by SnailBones — APPROVED** [review]

File: src/ui/map.js [hunk 1]
```diff
@@ -1198,6 +1201,7 @@ class Map extends Camera {
         let projectionHasChanged;
         // At high zoom on globe, set transform projection to Mercator while _explicitProjection stays globe.
         if (projection && projection.name === 'globe' && this.transform.zoom >= GLOBE_ZOOM_THRESHOLD_MAX) {
+            this._prevProjection = projection.name;
```
[the remark this answers is not in the document]
Comment (avpeery) [reply src/ui/map.js]: I moved setting it in one location altogether at the end of `map.updateProjection` like @SnailBones suggested (thanks @SnailBones )! Looking into the unit test failures now.

[the remark this answers is not in the document]
Comment (karimnaaji) [reply src/ui/map.js]: Sounds good!

File: src/ui/map.js [hunk 2]
```diff
@@ -1216,7 +1216,7 @@ class Map extends Camera {
 
         if (projectionHasChanged) {
             // If a zoom transition on globe
-            if (prevProjection.name === 'globe' && this.getProjection().name === 'globe') {
+            if (this._prevProjection && this._prevProjection.name === 'globe' && this.getProjection().name === 'globe') {
                 this.style._forceSymbolLayerUpdate();
             } else {
                 // If a switch between different projections
```
Comment (karimnaaji) [inline src/ui/map.js:1222]: This code path is already a bit complex and I'm worried about adding another state to track (`this._prevProjection`) considering we already have a few bugs with projection switching.

So maybe there's another way to go about fixing that, that may be simpler. If I understand the issue correctly, the displacement issue only happens when a switch between a non-mercator projection and globe projection happens.

If so, would the following work? This is untested code, but I'm curious about whether that would work:

```js
// We hit the threshold globe - mercator transition, only symbol relayout is necessary
const globeHasTransitioned = prevProjection.name === 'globe' && this.getProjection().name === 'globe';
if (globeHasTransitioned) {
    this.style._forceSymbolLayerUpdate();
}
// We switch between a projection with and without dynamic runtime reprojection
// Clearing tiles entirely is necessary
if (prevProjection.isReprojectedInTileSpace && !this.getProjection().isReprojectedInTileSpace) {
    // If a switch between different projections
    this.painter.clearBackgroundTiles();
    for (const id in this.style._sourceCaches) {
        this.style._sourceCaches[id].clearTiles();
    }
}
```

File: src/style/style.js [hunk 3]
```diff
@@ -311,6 +311,9 @@ class Style extends Evented {
 
         this._loaded = true;
         this.stylesheet = clone(json);
+
+        // store initial projection as prevProjection for checking clearing background tiles in `map.updateProjection`
+        this.map._prevProjection = this.map.getProjection();
```
Comment (karimnaaji) [inline src/style/style.js:316]: Maybe this could be at the beginning of `_updateMapProjection` so that it's not necessary to add it there?

Comment (avpeery) [reply src/style/style.js:316]: The issue is `style._updateMapProjection` is called in `style.setState` as well, but by the time `style._updateMapProjection` is called in `style.setState`, the result of `map.getProjection` is already updated to the current projection since the stylesheet is updated to the `nextState` in `style.setState`, so it is unable to get the previous map projection with this method at that time. So the same goes for `map.updateProjection` - by the time `setStyle` leads to `map.updateProjection` through `style.updateMapProjection`, it already updated `getProjection` to the current projection.

File: src/ui/map.js (hunk 2 above)
Comment (avpeery) [reply src/ui/map.js:1222]: @SnailBones also mentioned possibly using a zoom transition to check, so might look into that as well

File: src/style/style.js (hunk 3 above)
Comment (avpeery) [reply src/style/style.js]: Removed this logic and replaced with a forceSymbolLayerUpdate boolean argument for `updateProjection`

File: src/ui/map.js (hunk 2 above)
Comment (avpeery) [reply src/ui/map.js:1222]: `isReprojectedInTileSpace` did not work, but I changed to using a boolean argument in updateProjection to indicate "forceSymbolLayerUpdate"

Comment (avpeery) [reply src/ui/map.js:1221]: Hey thanks @karimnaaji - I got it to work using the `isReprojectedInTileSpace`. Using transform.projection allows capturing the prevProjection at the beginning of updateProjection as well.

I do think though we should be clearing tiles switching globe to mercator. I noticed with streets that it doesn't place symbols with this new setup and toggling globe -> mercator until interacting with the map.

Comment (SnailBones) [reply src/ui/map.js:1221]: The name `forceSymbolLayerUpdate` is incomplete, the full effect to choose between either updating symbols (on zoom transition) or clearing tiles (on projection change). IMO a more high level name, e.g. `globeZoomTransition` would better clarify the purpose of this argument.

I agree with the link shared by @karimnaaji that an object instead of argument is worth considering, this codepath shouldn't be called very often so I don't think performance will be an issue. On the other hand, the boolean trap is pretty widespread in our code already.

Comment (karimnaaji) [reply src/ui/map.js:1221]: >I do think though we should be clearing tiles (or force symbol placement) switching globe to mercator. I noticed with streets that it doesn't place symbols with this new setup and toggling globe -> mercator until interacting with the map.

>But as @avpeery mentions above I think this is missing the edge case when a developer switches between globe and Mercator projection. In this case, I think we want the same behavior as other projection switches, i.e. clearing tiles and not forcing a symbol layer update.

I think that reloading tiles is already a process already involving symbol relayout since everything gets dropped anyway, so maybe we can simplify it to doing it every time we have a projection change? Like so:

```
if (projectionHasChanged) {
  this.style._forceSymbolLayerUpdate();
  if (this.transform.projection.isReprojectedInTileSpace || prevProjectionReprojected) {
    // reload tiles
  }
}
```

Comment (avpeery) [reply src/ui/map.js:1221]: @karimnaaji We could flip it. so an "else" trigger the forceSymbolLayerUpdate. Feels redundant to force symbol layer update and then trigger clearing tiles.

Comment (avpeery) [reply src/ui/map.js]: Working on the render-tests tbd!

Comment (SnailBones) [reply src/ui/map.js:1221]: > I think that reloading tiles is already a process involving symbol update since everything gets dropped anyway, so maybe we can simplify it to doing it every time we have a projection change? Like so:

@karimnaaji I like that this makes it clear that one update is more thorough than the other. But are we confident that the additional calls to `_updateLayer` won't affect performance?

Comment (avpeery) [reply src/ui/map.js:1221]: @karimnaaji and @SnailBones - I tested out this proposed approach but the call to forceSymbolLayerUpdate broke at least 20 render tests failing to place symbols on globe. I feel like it's too risky of a change and I think being intentional about what the forceSymbolLayerUpdate is supposed to do (i.e. avoiding clearing all the tiles when it's a globe transition) is the better approach

File: src/geo/transform.js [hunk 4]
```diff
@@ -149,6 +149,7 @@ class Transform {
     _nearZ: number;
     _farZ: number;
     _mercatorScaleRatio: number;
+    _globeZoomTransition: boolean;
```
Comment (SnailBones) [inline src/geo/transform.js:152]:
```suggestion
    _globeZoomTransition: boolean;
```
I'm not sure about staring this value in `transform`, it seems simpler just to pass it through `map._updateProjection`. Or do we anticipate a need to use this value elsewhere?

Comment (avpeery) [reply src/geo/transform.js:152]: Ah was trying to avoid the confusing passing of arguments. seeing your comment about an object is better than boolean (will change)

File: src/ui/map.js [hunk 5]
```diff
@@ -3074,9 +3073,11 @@ class Map extends Camera {
         if (this.getProjection().name === 'globe') {
             if (this.transform.zoom >= GLOBE_ZOOM_THRESHOLD_MAX) {
                 if (this.transform.projection.name === 'globe') {
+                    this.transform._globeZoomTransition = true;
```
Comment (SnailBones) [inline src/ui/map.js:3076]: As above, changing `transform` state seems unecessary to me. @avpeery @karimnaaji Thoughts on something like the following?
```js
                    this._updateProjection({zoomTransition: true});
```
Alternatively, perhaps we could break `map._updateProjection` into two functions called something like `_changeProjection` and `_transitionGlobeProjection`, which would each call a common function before performing the conditional update?

File: src/ui/map.js (hunk 2 above)
Comment (karimnaaji) [reply src/ui/map.js:1221]: @avpeery it might be important to understand why, as this might give us more clue towards simplifying and refactoring this part of the code. 

>But are we confident that the additional calls to _updateLayer won't affect performance?

I can't say for sure whether it affects performance, it could be worth for @avpeery to benchmark the final solution to ensure that once it's finalized. But as this isn't a hot code path and this might be negligible, I'm leaning towards ensuring that we keep the logic as simple as possible.

File: src/ui/map.js (hunk 5 above)
Comment (karimnaaji) [reply src/ui/map.js]: >Alternatively, perhaps we could break map._updateProjection into two functions called something like _changeProjection and _transitionGlobeProjection, which would each call a common function before performing the conditional update?

I agree, splitting things up would make sense. Most of this logic doesn't need to be shared and this function tries to do too much. It's mainly the reason why we have this issue in the first place. I'm not sure about the common function, but I gave it a quick try at separating the concerns of these two different code paths in https://github.com/mapbox/mapbox-gl-js/commit/3aa06d09ca48ff24850cdf548a9665ab4ce8d8d6 as an example to better support this suggestion

File: test/unit/ui/map.test.js [hunk 6]
```diff
@@ -1900,20 +1900,20 @@ test('Map', (t) => {
                 // Defaults to style projection
                 t.equal(style.serialize().projection.name, 'globe');
                 t.equal(map.transform.getProjection().name, 'globe');
-                t.equal(map.painter.clearBackgroundTiles.callCount, 0);
+                t.equal(map.painter.clearBackgroundTiles.callCount, 1);
```
Comment (SnailBones) [inline test/unit/ui/map.test.js:1903]: Are we confident that there's no regression to map load time caused by this additional call to `clearBackgroundTiles`?

File: src/ui/map.js [hunk 7]
```diff
@@ -1185,49 +1190,53 @@ class Map extends Camera {
...
-        // When called through setProjection, update _explicitProjection
-        if (explicitProjection) {
-            this._explicitProjection = (explicitProjection.name === "globe" ?
-                {name:'globe', center:[0, 0]} :
-                this.transform.getProjection());
+        if (projectionHasChanged) {
+            this.style.applyProjectionUpdate();
+            this.style._forceSymbolLayerUpdate();
+        }
+    }
```
Comment (SnailBones) [inline src/ui/map.js:1217]: This function is much easier to read, nice work!

File: src/ui/map.js [hunk 8]
```diff
@@ -1185,49 +1190,53 @@ class Map extends Camera {
...
-        // At high zoom on globe, set transform projection to Mercator while _explicitProjection stays globe.
-        if (projection && projection.name === 'globe' && this.transform.zoom >= GLOBE_ZOOM_THRESHOLD_MAX) {
-            projectionHasChanged = this.transform.setProjection({name: 'mercator'});
-            this.transform.mercatorFromTransition = true;
-        } else {
-            projectionHasChanged = this.transform.setProjection(projection);
-            this.transform.mercatorFromTransition = false;
+
+        if (projection === 'globe' && tr.zoom >= GLOBE_ZOOM_THRESHOLD_MAX) {
+            projectionHasChanged = tr.setMercatorFromTransition();
```
Comment (SnailBones) [inline src/ui/map.js:1208]: If this condition is true`projectionHasChanged` will always be truthy, perhaps we can make the logic clearer by removing the function result
```suggestion
            tr.setMercatorFromTransition();
            projectionHasChanged = true;
```

File: src/ui/map.js [hunk 9]
```diff
@@ -1185,49 +1190,53 @@ class Map extends Camera {
...
+        }
+    }
+
+    _updateProjection(): this {
+        //check explicit projection separately as transform.projection hasn't been updated yet
+        const projection = this._explicitProjection || this.getProjection();
+        let projectionHasChanged;
+
+        if (projection.name === 'globe' && this.transform.zoom >= GLOBE_ZOOM_THRESHOLD_MAX) {
+            projectionHasChanged = this.transform.setMercatorFromTransition();
```
Comment (SnailBones) [inline src/ui/map.js:1225]: Currently `setMercatorFromTransition` always returns true, but `transform.projection` hasn't changed in the case where we switch Mercator to Globe at high zoom. (This may be why we're seeing an extra call to`clearBackgroundTiles` in the unit test).

Should `transform.setMercatorFromTransition()` return whether the projection has updated similar to `transform.setProjection`?
https://github.com/mapbox/mapbox-gl-js/blob/4130912ec4fa859bae4d033479360c5679aa3db1/src/geo/transform.js#L250-L255

File: src/style/style.js [hunk 10]
```diff
@@ -365,9 +365,7 @@ class Style extends Evented {
         } else {
             delete this.stylesheet.projection;
         }
-        if (!this.map._explicitProjection) {
-            this.map._updateProjection();
-        }
+        this._updateMapProjection();
```
Comment (SnailBones) [inline src/style/style.js:368]: This change may impact performance as it triggers an extra `setProjection` worker event in cases where `map.explicitProjection !== null` (i.e. when the map remains unchanged)

File: src/style/style.js [hunk 11]
```diff
@@ -662,7 +660,7 @@ class Style extends Evented {
         }
 
         changes.forEach((op) => {
-            if (op.command === 'setTransition') {
+            if (op.command === 'setTransition' || op.command === 'setProjection') {
                 // `transition` is always read directly off of
```
Comment (SnailBones) [inline src/style/style.js:664]:
```suggestion
                // `transition` and `projection` are always read directly from
```

File: src/ui/map.js [hunk 12]
```diff
@@ -1185,45 +1190,52 @@ class Map extends Camera {
         } else if (typeof projection === 'string') {
             projection = (({name: projection}: any): ProjectionSpecification);
         }
-        return this._updateProjection(projection);
+        this._explicitProjection = projection;
+        return this._updateProjection();
```
Comment (SnailBones) [inline src/ui/map.js:1194]: Nice work removing the argument from `_updateProjection` 👍

File: src/ui/map.js [hunk 13]
```diff
@@ -1143,11 +1143,16 @@ class Map extends Camera {
      */
     getProjection(): ProjectionSpecification {
         if (this._explicitProjection) {
-            return this._explicitProjection;
+            if (this.transform.mercatorFromTransition) {
+                return {name: "globe", center: [0, 0]};
+            }
+            return this.transform.getProjection();
```
Comment (SnailBones) [inline src/ui/map.js:1149]: If we're keeping `_explicitProjection` as a projection object (not a boolean),  can the simpler` return this._explicitProjection;` work here?

File: src/ui/map.js [hunk 14]
```diff
@@ -1185,45 +1190,52 @@ class Map extends Camera {
...
-                this.transform.getProjection());
+        if (projectionHasChanged) {
+            this.style.applyProjectionUpdate();
+            this.style._forceSymbolLayerUpdate();
+        }
+    }
+
+    _updateProjection(): this {
+        // Check explicit projection separately as transform.projection hasn't been updated yet
+        const projection = this._explicitProjection || this.getProjection();
```
Comment (SnailBones) [inline src/ui/map.js:1222]: As above, so long as `_explicitProjection` is a projection object, can we place this logic in `getProjection` and simplify this to:
```suggestion
        const projection = this.getProjection();
```

File: src/ui/map.js [hunk 15]
```diff
@@ -1143,11 +1143,16 @@ class Map extends Camera {
...
+                return {name: "globe", center: [0, 0]};
+            }
+            return this.transform.getProjection();
         }
+
         if (this.style && this.style.stylesheet && this.style.stylesheet.projection) {
             return this.style.stylesheet.projection;
         }
+
         return {name: "mercator", center:[0, 0]};
```
[the remark this answers is not in the document]
Comment (avpeery) [reply src/ui/map.js:1156]: I can add this in like so `const projection = this._explicitProjection || (this.style.stylesheet && this.style.stylesheet.projection) || this.getProjection();` to remove it from getProjection; however, what about returning mercator when it's null?

[the remark this answers is not in the document]
Comment (SnailBones) [reply src/ui/map.js:1156]: > I can add in checking stylesheet like so in updateProjection `const projection = this._explicitProjection || (this.style.stylesheet && this.style.stylesheet.projection) || this.getProjection();` to remove it from getProjection; however, what about returning mercator when it's null?

> Is it possible for the style to have a projection but not have it in the transform?

I think the transform always has a projection, i.e. `transform.getProjection()` will return a Mercator projection in cases when a projection has not been set or when `_explicitProjection` and `stylesheet.projection` are null.

[the remark this answers is not in the document]
Comment (SnailBones) [reply src/ui/map.js:1156]: > I can add in checking stylesheet like so in updateProjection `const projection = this._explicitProjection || (this.style.stylesheet && this.style.stylesheet.projection) || this.getProjection();` to remove it from getProjection; however, what about returning mercator when it's null?

@avpeery I misunderstood what you meant here, good catch that this won't trigger an update to Mercator when setting `stylesheet.projection` to null! Here's a fix:
 
```js
_updateProjection(explicitProjection?: ProjectionSpecification): this {
   const projection = explicitProjection ||
      (!this._useStyleProjection && this.getProjection()) ||
      (this.style.stylesheet && this.stylesheet.projection) ||
      {name: "mercator", center:[0, 0]})
```
There's probably a more readable way to write this but I think that is the correct order of precedence (explicit projection (now transform projection) > style projection > Mercator fallback)

[the remark this answers is not in the document]
Comment (avpeery) [reply src/ui/map.js:1156]: Currently it doesn't - Looking into a change to this

[the remark this answers is not in the document]
Comment (avpeery) [reply src/ui/map.js:1156]: Sorry for the unclear comment - it seem it is returning mercator initially, but if trying to unset a previous projection with `map.getProjection(null)` does not result in a change to mercator with this change (stays as previous projection)

[the remark this answers is not in the document]
Comment (avpeery) [reply src/ui/map.js]: Replaced with the function selectProjectionByProjection. Thanks @karimnaaji for this suggestion, it's much more readable!

File: src/ui/map.js (hunk 9 above)
Comment (avpeery) [reply src/ui/map.js]: Hey @SnailBones, can you elaborate on this? It's getting specifically called on a transition from globe -> mercator and not mercator -> globe. It's only called [here at map.js line 1204](https://github.com/mapbox/mapbox-gl-js/blob/a62035e9e18ae454e04d2cd637f4d3e11df01979/src/ui/map.js#L1204) and [here at map.js line 1221](https://github.com/mapbox/mapbox-gl-js/blob/a62035e9e18ae454e04d2cd637f4d3e11df01979/src/ui/map.js#L1221). I also checked that this proposed change would break toggling between mercator and globe at a high zoom. If I toggle globe -> mercator -> globe at a high zoom with setProjection and then zoom back out, this change doesn't register the change to back to globe projection and is still mercator.

**Review by karimnaaji — APPROVED** [review]
Looks good to me! Thanks for carrying all of these simplifications forward @avpeery

File: test/unit/ui/map.test.js (hunk 6 above)
Comment (SnailBones) [reply test/unit/ui/map.test.js:1903]: Just chatted with @karimnaaji about this, benchmarks don't currently implement any non-Mercator projections.

Still, there's probably little to no performance impact here.`clearBackgroundTiles` is a trivial function. https://github.com/mapbox/mapbox-gl-js/blob/5d2b1381b2250633091fef04fe5d681a7795f093/src/render/painter.js#L1027-L1029. The following source cache clearing might be more expensive but might not be an issue if this runs before tiles load.

My previous hypothesis about why this is happening may not be correct since the map seem to be at default zoom 0 here. If there's any easy fix to keep the test the same I think that would be ideal, but this is probably fine.

File: src/ui/map.js (hunk 9 above)
Comment (SnailBones) [reply src/ui/map.js]: > Hey @SnailBones, can you elaborate on this?

When we change the style projection from Mercator to Globe at high zoom, we shouldn't clear tiles. (This is currently exacerbated by [unecessary calls to _updateProjection](https://github.com/mapbox/mapbox-gl-js/pull/12049#discussion_r916042902), in combination these result in clearing tiles on every style change while the projection is in globe by high zoom).

> I also checked that this proposed change would break toggling between mercator and globe at a high zoom. If I toggle globe -> mercator -> globe at a high zoom with setProjection and then zoom back out, this change doesn't register the change to back to globe projection and is still mercator.

Can you elaborate on what exactly you changed to see this behavior? I think that the correct behavior should result when this call in `_updateProjection` to be changed to:
```js
           projectionHasChanged = this.transform.setMercatorFromTransition();
```
while the call in `_updateProjectionTransition() should remain unaffected by the result:
```js
            tr.setMercatorFromTransition();
            projectionHasChanged = true;
```
but I may be wrong about that.

File: src/style/style.js [hunk 16]
```diff
@@ -662,16 +653,16 @@ class Style extends Evented {
...
+                // `transition` and `projection` are always read directly from
                 // `this.stylesheet`, which we update below
                 return;
             }
             (this: any)[op.command].apply(this, op.args);
         });
 
         this.stylesheet = nextState;
-        this._updateMapProjection();
+        this.map._updateProjection(selectProjectionByPriority(this.map._explicitProjection, this.stylesheet.projection));
```
[the remark this answers is not in the document]
Comment (SnailBones) [reply src/style/style.js:665]: cc @karimnaaji noticing this change came from [your example](https://github.com/mapbox/mapbox-gl-js/commit/44837ecc55641e5441bb512185540ea908e1c8c4).

I think that the performance impact of these additional call to `map._updateProjection` should be negligible so long as `projectionHasChanged` returns false in these cases. However, that's not currently the case as in cases with an explicit projection of globe above the Mercator transition zoom, we're clearing tiles on style projection updates that should have no visible affect, as I discuss [here](https://github.com/mapbox/mapbox-gl-js/pull/12049#discussion_r915042458).

File: src/style/style.js [hunk 17]
```diff
@@ -365,17 +366,7 @@ class Style extends Evented {
         } else {
             delete this.stylesheet.projection;
         }
-        if (!this.map._explicitProjection) {
```
[the remark this answers is not in the document]
Comment (avpeery) [reply src/style/style.js:368]: Ah OK that was what I was debating readability versus performance impact. No harm adding the conditional back in

File: src/ui/map.js (hunk 9 above)
Comment (avpeery) [reply src/ui/map.js]: OK I found a change that does cause the bug I noted above and does compare old projection and new projection. I'll add in a test case to make sure the we don't stumble into the bug I discovered above

File: src/ui/map.js [hunk 18]
```diff
@@ -1185,49 +1190,53 @@ class Map extends Camera {
...
-            projectionHasChanged = this.transform.setProjection({name: 'mercator'});
-            this.transform.mercatorFromTransition = true;
-        } else {
-            projectionHasChanged = this.transform.setProjection(projection);
-            this.transform.mercatorFromTransition = false;
+
+        if (projection === 'globe' && tr.zoom >= GLOBE_ZOOM_THRESHOLD_MAX) {
+            projectionHasChanged = tr.setMercatorFromTransition();
+        } else if (projection === 'mercator' && tr.zoom < GLOBE_ZOOM_THRESHOLD_MAX) {
+            projectionHasChanged = tr.setProjection({name: 'globe'});
```
[the remark this answers is not in the document]
Comment (avpeery) [reply src/ui/map.js:1208]: If we are already running setProjection that will return true here I'm not sure separating out makes sense if it is going to be going to be running `setProjection` returning the boolean regardless.

File: src/style/style.js [hunk 19]
```diff
@@ -311,7 +312,7 @@ class Style extends Evented {
 
         this._loaded = true;
         this.stylesheet = clone(json);
-        this._updateMapProjection();
+        this.map._updateProjection(selectProjectionByPriority(this.map._explicitProjection, this.stylesheet.projection));
```
[the remark this answers is not in the document]
Comment (avpeery) [reply src/style/style.js:315]: I think the point was to make it apparent that these arguments were being passed into updateProjection. The issue with using `getProjection` to set the new projection is that it hasn't updated yet, so `getProjection` would be referencing the previous projection until the `tr.setProjection` calls in _updateProjection

[the remark this answers is not in the document]
Comment (avpeery) [reply src/style/style.js:315]: Would it help to pull out the `selectProjectionByPriority` function from the argument to determine the prioritizedProjection and then pass that in?

File: src/style/style.js (hunk 10 above)
Comment (avpeery) [reply src/style/style.js]: Added conditional back in

File: src/style/style.js (hunk 19 above)
[the remark this answers is not in the document]
Comment (SnailBones) [reply src/style/style.js]: Your changes look good to me! One final nit is to replace `map._updateProjection` with a boolean.

File: test/unit/style/style.test.js [hunk 20]
```diff
@@ -2447,6 +2447,9 @@ test('Style#setProjection', (t) => {
         style.map._update = () => {};
         style.map.setProjection = (projection) => {
             style.map._explicitProjection = projection;
+            style.map._prioritizeAndUpdateProjection();
+        };
+        style.map._prioritizeAndUpdateProjection = () => {
```
Comment (SnailBones) [inline test/unit/style/style.test.js:2452]: Nit: given the changes to the source, would it be possible to actually test  `_prioritizeAndUpdateProjection()` instead of mocking it as we do here? 

One idea would be to mock `map._updateProjection` to set an `explicitProjection` variable, and then check the set value after each call to `_prioritizeAndUpdateProjection`

As this logic is in `map`, maybe this would work better in `map.test.js`

Comment (SnailBones) [reply test/unit/style/style.test.js:2452]: On second thought, this test is identical to this one in map.test.js: https://github.com/mapbox/mapbox-gl-js/blob/d821c49a4021859a8109c8f14020e2600a84b347/test/unit/ui/map.test.js#L1836-L1884

I'd lean toward removing this test entirely in favor of the more thorough version in map.test.js, not sure what I was thinking when I created the duplicate test!

Comment (avpeery) [reply test/unit/style/style.test.js]: Oops! sounds good, they are identical! let's use the one in map.test.js since we don't have to mock the functions!

**Review by SnailBones — APPROVED** [review]
Everything looks good to me! Nice work @avpeery and @karimnaaj with an important fix, nice tests and huge readability improvement to a gnarly part of the code.
