### PR TITLE
provide helpful message if access token triggers 401: Unauthorized

### LINKED ISSUE #5852: Friendly message when malformed accessToken provided
I copied an example while not logged in:

```...
<script>
mapboxgl.accessToken = '<your access token here>';
var map = new mapboxgl.Map({
...
```

Not surprisingly it didn't work. More surprisingly, there's not a helpful error message in the console, just:

```
Object { status: 401, stack: "" }
```

Prior to version 0.35.0, this produced a slightly more (maybe) useful error message:

```
Error: Unauthorized
Stack trace:
[191]</exports.getJSON/n.onload@https://api.tiles.mapbox.com/mapbox-gl-js/v0.34.0/mapbox-gl.js:392:513
```

Suggestion: throw the same error as when no `accessToken` is set at all:

```
Error: An API access token is required to use Mapbox GL. See https://www.mapbox.com/api-documentation/#access-tokens
```

Currently the "helpful" line of code ` mapboxgl.accessToken = '<your access token here>';` is actually making things worse for the newbie.

An alternative is to simply comment that line out in every example.

(Nitpick: technically the error message is not accurate. Mapbox-GL-JS works just fine without an access token, as long as you're not accessing any Mapbox services.)

### PR DESCRIPTION
**Pull request by mollymerp**
fix #5852 

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] write tests for all new functionality
 - [x] manually test the debug page

### CODE REVIEW

File: src/util/ajax.js [hunk 1]
```diff
@@ -85,7 +85,11 @@ exports.getJSON = function(requestParameters: RequestParameters, callback: Callb
             }
             callback(null, data);
         } else {
-            callback(new AJAXError(xhr.statusText, xhr.status, requestParameters.url));
+            if (xhr.status === 401) {
```
Comment (lucaswoj) [inline src/util/ajax.js]: What do you think about also testing the URL is on the `mapbox.com` domain? So long as we promise [compatibility with third party vector tile sources](https://www.mapbox.com/mapbox-gl-js/example/third-party/) we must be careful with logic that assumes we're talking to Mapbox servers.

Comment (mollymerp) [reply src/util/ajax.js]: good idea!
