### PR TITLE
Fix `undefined is not an object` warning (Safari)

### LINKED ISSUE #11095: TypeError: undefined is not an object (evaluating 't[12]') on Safari 15.0
Sentry Issue: [GL-JS-EXAMPLES-H9](https://sentry.io/organizations/mapboxcom/issues/2686830201/?referrer=github_integration)

```
TypeError: undefined is not an object (evaluating 't[12]')
  at set (../src/render/uniform_binding.js:121:13)
  at draw (../src/render/program.js:196:38)
  at drawSymbolElements (../src/render/draw_symbol.js:399:13)
  at drawLayerSymbols (../src/render/draw_symbol.js:392:9)
  at type (../src/render/draw_symbol.js:87:9)
...
(4 additional frame(s) were not displayed)
```

- browser: Safari 15.0
- device: Mac
- os: Mac OS X 10.15.7

Demos that are logging the TypeError:
- https://docs.mapbox.com/mapbox-gl-js/assets/set-perspective-demo.html
- https://docs.mapbox.com/mapbox-gl-js/assets/cluster-demo.html
- https://docs.mapbox.com/mapbox-gl-js/assets/third-party-demo.html
- https://docs.mapbox.com/mapbox-gl-js/assets/geojson-line-demo.html
- https://docs.mapbox.com/mapbox-gl-js/assets/variable-label-placement-demo.html
- https://docs.mapbox.com/mapbox-gl-js/assets/simple-map-demo.html
- https://docs.mapbox.com/mapbox-gl-js/assets/marker-from-geocode-demo.html
- https://docs.mapbox.com/mapbox-gl-js/assets/image-on-a-map-demo.html
- https://docs.mapbox.com/mapbox-gl-js/assets/flyto-demo.html
- https://docs.mapbox.com/mapbox-gl-js/assets/filter-features-within-map-view-demo.html
- https://docs.mapbox.com/mapbox-gl-js/assets/canvas-source-demo.html

### PR DESCRIPTION
**Pull request by avpeery**
Closes #11095. After debugging, the t[12] issue is most likely a webkit bug issue. When throwing an error with the name and value of uniformValues if `uniformValues[name] === undefined` at [line 214 in program.js](https://github.com/mapbox/mapbox-gl-js/blob/main/src/render/program.js#L214), the name is always `u_is_size_zoom_constant` and value is always defined as 0. When changing the `for in` loop to a `for of` loop,  the error is not thrown after multiple attempts using the same interaction to trigger. Simply using a check for if uniformValues[name] is undefined hides the warning but still triggers the rendering issue (usually displayed by missing text inside of icons with text or missing text on streets).

You can trigger the error by opening Safari 15 in a private window, emptying the cache, and zooming in/out in a slow-to-medium motion using debug/index.html. 

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] manually test the debug page
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'

### CODE REVIEW

File: src/render/uniform_binding.js [hunk 1]
```diff
@@ -118,16 +118,19 @@ class UniformMatrix4f extends Uniform<Float32Array> {
...
         // happen at i=12 or i=0, so we check those first to avoid lots of
         // unnecessary iteration:
-        if (v[12] !== this.current[12] || v[0] !== this.current[0]) {
-            this.current = v;
-            this.gl.uniformMatrix4fv(this.location, false, v);
-            return;
-        }
-        for (let i = 1; i < 16; i++) {
-            if (v[i] !== this.current[i]) {
+        if (v !== undefined) {
```
Comment (mourner) [inline src/render/uniform_binding.js:121]: Nit: instead of wrapping the whole method in an `if` block, it's usually preferable to add an early return (e.g. `if (!v) return`). Makes it more readable.

**Review by mourner — APPROVED** [review]

**Comment by karimnaaji** [comment]
@avpeery I think this PR deserves a changelog entry, as it fixes something that isn't working properly working in another version.
