### PR TITLE
Fix unstable symbol rendering order

### LINKED ISSUE #1558: draw priority is unstable in gl js
I wish I could find better examples of this problem, but: 

- Sometimes labels from one layer show up at the exact location on one refresh, and are gone on the next refresh. 
- Sometimes layers lower in the order seem to have draw priority _above_ layers higher in the stack.

### PR DESCRIPTION
**Pull request by lucaswoj**
The order of the layers we pass to `WorkerTile` is related to the order that they were added to the stylesheet, not their logical order. 

fixes #1558

cc @scothis @samanpwbb

### CODE REVIEW

**Comment by lucaswoj** [comment]
We also do a `for ... in` iteration over an object in [worker_tile.js:101](https://github.com/mapbox/mapbox-gl-js/blob/master/js/source/worker_tile.js#L101) but I don't think that'll cause any problems (in the browsers that we support)

**Comment by scothis** [comment]
Doing a for-in over bucketsById is ok as long as the resulting arrays are treated like sets instead of ordered arrays.

File: js/style/style.js [hunk 1]
```diff
@@ -172,13 +172,9 @@ Style.prototype = util.inherit(Evented, {
     },
 
     _broadcastLayers: function() {
-        var ordered = [];
-
-        for (var id in this._layers) {
-            ordered.push(this._layers[id].json());
-        }
```
Comment (lucaswoj) [inline js/style/style.js]: While not in the official spec, all major JS interpreters will iterate over objects in the order that the keys were added. 

If a call to `addLayer` specifies a `before` parameter, it'll end up at the end of this array, even though it was intended for elsewhere. Then, during label placement in the worker, the layer will not be ordered correctly.

**Comment by mcwhittemore** [comment]
Using _order looks safe to me. :+1:
