### PR TITLE
fix dash lengths

### LINKED ISSUE #3426: Ensure "line-dasharray" works as specified when "line-width" changes at runtime
https://github.com/mapbox/mapbox-gl-test-suite/tree/master/render-tests/regressions/mapbox-gl-js%233426

Expected:

image

Actual:

image

### PR DESCRIPTION
**Pull request by ansis**
First commit fixes a regression where the dash length was based on the first fractional zoom reached instead of the integer zoom level. [I added a new render test](https://github.com/mapbox/mapbox-gl-test-suite/commit/031ec5fde2a8b4b47603f9bb808705d4f0f8edb4). See commit message for details.

The second commit fixes #3426 (dash length when line width changes at runtime).

:eyes: @lucaswoj 

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] write tests for all new functionality
 - [x] document any changes to public APIs
 - [x] post benchmark scores
 - [x] manually test the debug page

benchmark | master adf0df8 | master bfe3b2b
--- | --- | ---
**map-load** | 245 ms  | 139 ms 
**style-load** | 146 ms  | 143 ms 
**buffer** | 1,195 ms  | 1,227 ms 
**fps** | 60 fps  | 60 fps 
**frame-duration** | 7.7 ms, 1% > 16ms  | 7.9 ms, 3% > 16ms 
**query-point** | 1.11 ms  | 1.20 ms 
**query-box** | 89.36 ms  | 93.97 ms 
**geojson-setdata-small** | 7 ms  | 7 ms 
**geojson-setdata-large** | 124 ms  | 111 ms

### CODE REVIEW

File: js/style/style_layer/line_style_layer.js [hunk 1]
```diff
@@ -10,11 +11,9 @@ class LineStyleLayer extends StyleLayer {
...
         // width at the previous round zoom level.
         if (value && name === 'line-dasharray') {
-            const flooredZoom = Math.floor(globalProperties.zoom);
-            if (this._flooredZoom !== flooredZoom) {
-                this._flooredZoom = flooredZoom;
-                this._flooredLineWidth = this.getPaintValue('line-width', globalProperties, featureProperties);
-            }
+            const flooredGlobalProperties = util.clone(globalProperties);
+            flooredGlobalProperties.zoom = Math.floor(globalProperties.zoom);
+            this._flooredLineWidth = this.getPaintValue('line-width', flooredGlobalProperties, featureProperties);
```
Comment (jfirebaugh) [inline js/style/style_layer/line_style_layer.js]: Is there a need to keep the instance variable or can this be `const flooredLineWidth = ...`?

Comment (jfirebaugh) [inline js/style/style_layer/line_style_layer.js]: I'd probably write:

```js
const width = this.getPaintValue('line-width',
    util.extend({}, globalProperties, {zoom: Math.floor(globalProperties.zoom)}), featureProperties);
```

But my main point is that I don't think the result needs to be stored as `this._flooredLineWidth`. It can just be a local variable.

Comment (ansis) [inline js/style/style_layer/line_style_layer.js]: nope, no need. fixed

**Comment by jfirebaugh** [comment]
Oh, don't forget to remove the ignore from https://github.com/mapbox/mapbox-gl-test-suite/tree/master/render-tests/regressions/mapbox-gl-js%233426.
