### PR TITLE
Fix clamping behavior of pointCoordinate leading to false positives in feature queries 

### LINKED ISSUE #11746: Clamping behavior of `pointCoordinate` leads to false positives in feature queries
Feature querying uses `pointCoordinate` functionality for projecting screen rectangles into query polygons. Globe view implementation of the function clamps the query ray to the horizon of the globe as the function signature does not allow null values. This has a side effect of returning features at the horizon line due to the clamping:

https://user-images.githubusercontent.com/7061573/163066618-db297271-4c5e-4983-877d-aad92f9e1442.mov

Perhaps we could consider modifying the function and allow returning null values?

### PR DESCRIPTION
**Pull request by SnailBones**
Fixes #11746

Before:

https://user-images.githubusercontent.com/14878684/167700505-9f3baadc-743f-412f-b12d-81725b0dd1a3.mov

After:

https://user-images.githubusercontent.com/14878684/167700514-507c1ab1-c5f3-400d-80af-1ba1fdb4a670.mov

For box queries, this PR correctly fixes cases where the box is outside of the globe. However, in the edge case where the edges of the box are off the globe but the bottom of the box intersects the globe, the query returns empty.

https://user-images.githubusercontent.com/14878684/167741209-8ea46f45-ad8a-4061-b229-5943f5a2015a.mov

In lieu of a more involved fix, one option worth considering would reenabling clamping for all box queries, in which case queries above the horizon will in effect query the horizon line beneath.

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [X] include before/after visuals or gifs if this PR includes visual changes
 - [ ] write tests for all new functionality
 - [X] manually test the debug page
 - [ ] tagged `@mapbox/gl-native` if this PR includes shader changes or needs a native port
 - [X] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'

### CODE REVIEW

File: src/geo/projection/projection.js [hunk 1]
```diff
@@ -98,6 +98,14 @@ export default class Projection {
         }
     }
 
+    isPointAboveHorizon(tr: Transform, p: Point): boolean {
```
Comment (karimnaaji) [inline src/geo/projection/projection.js:101]: :+1: that's a nice way to fork the behavior and do that only when needed.

I think it's also important that we reject similar queries for points that fall outside the globe on `map.getElevation` queries.

Comment (SnailBones) [reply src/geo/projection/projection.js:101]: > I think it's also important that we reject similar queries for points that fall outside the globe on map.getElevation queries.

@karimnaaji Can you elaborate on this and why it is the desired behavior?

Comment (karimnaaji) [reply src/geo/projection/projection.js:101]: For similar reasons as it is a desired behavior for feature querying, refer https://github.com/mapbox/mapbox-gl-native-internal/issues/3343 for `map.getElevation`. These querying APIs should adopt _what you see is what you get_ (WYSIWYG), otherwise we fail at a 1:1 matching between what you're actually querying and what you're getting back. Why would we ever want screen points outside the globe to resolve elevation incorrectly at points on the horizon?

File: src/geo/projection/globe_util.js [hunk 2]
```diff
@@ -52,6 +52,69 @@ const GLOBE_LOW_ZOOM_TILE_AABBS = [
     new Aabb([0, 0, GLOBE_MIN], [GLOBE_MAX, GLOBE_MAX, GLOBE_MAX])  // x=1, y=1
 ];
 
+export function globePointCoordinate(tr: Transform, x: number, y: number, clampToHorizon: boolean = true): ?MercatorCoordinate {
```
Comment (mpulkki-mapbox) [inline src/geo/projection/globe_util.js:55]: Should we change the function signature to return non-nullable mercator coordinate?

File: src/geo/projection/projection.js [hunk 3]
```diff
@@ -98,6 +98,14 @@ export default class Projection {
...
+        if (tr.elevation) {
+            return !this.pointCoordinate3D(tr, p.x, p.y);
+        }
```
Comment (mpulkki-mapbox) [inline src/geo/projection/projection.js:104]: Is this valid for other projections such as mercator? Does `false` returned from `pointCoordinate3D` imply that the point is above horizon?

File: src/geo/projection/projection.js (hunk 1 above)
Comment (SnailBones) [reply src/geo/projection/projection.js:101]: Good idea @karimnaaji, that makes sense! Adding a helper should be as simple as publicly exposing  `isPointAboveHorizon`, though the latter approach would save a raytracing call so might improve performance. Let's keep this in mind for a future feature!

File: src/geo/projection/projection.js (hunk 3 above)
Comment (SnailBones) [reply src/geo/projection/projection.js:104]: > Is this valid for other projections such as mercator?

@mpulkki-mapbox Yes, this is valid for all non-globe projections. (I've moved this code from `transform.js`.)

> Does `false` returned from `pointCoordinate3D` imply that the point is above horizon?

Yes, it returns `null` in this case, passed from [`terrain.pointCoordinate`](https://github.com/mapbox/mapbox-gl-js/blob/51d405880c34606fb28b0cb411be03335f37d671/src/terrain/terrain.js#L1185).

Comment (karimnaaji) [reply src/geo/projection/projection.js:104]: >>Is this valid for other projections such as mercator?
>
>@mpulkki-mapbox Yes, this is valid for all non-globe projections. (I've moved this code from transform.js.)

Yes I think this only gets resolved when terrain is enabled, refer [here](https://github.com/mapbox/mapbox-gl-js/blob/main/src/terrain/terrain.js#L1207). Otherwise we're always returning a valid coordinate, it's a difficult code path to follow because we're always checking against terrain. That's our full code path for non-globe projection:

```js
pointCoordinate3D(tr: Transform, x: number, y: number): ?Vec3 {
    const p = new Point(x, y);
    if (tr.elevation) {
        return tr.elevation.pointCoordinate(p); // null when dem tree raycast fails
    } else {
        const mc = this.pointCoordinate(tr, p.x, p.y, 0);
        return [mc.x, mc.y, mc.z]; // never null
    }
}
```

File: src/geo/projection/projection.js [hunk 4]
```diff
@@ -98,6 +98,14 @@ export default class Projection {
         }
     }
 
+    isPointAboveHorizon(tr: Transform, p: Point): boolean {
+        if (tr.elevation) {
+            return !this.pointCoordinate3D(tr, p.x, p.y);
```
Comment (karimnaaji) [inline src/geo/projection/projection.js:103]: nit: It might be nice to introduce a named variable so we're able to reason about that while reading it to make it explicit:

```suggestion
        if (tr.elevation) {
            const raycastOnTerrain = this.pointCoordinate3D(tr, p.x, p.y);
            return !raycastOnTerrain;
```

File: src/geo/projection/globe.js [hunk 5]
```diff
@@ -97,69 +95,18 @@ export default class Globe extends Mercator {
...
 
     pointCoordinate3D(tr: Transform, x: number, y: number): ?Vec3 {
-        const mc = this.pointCoordinate(tr, x, y, 0);
-        return [mc.x, mc.y, mc.z];
+        const coord = this.pointCoordinate(tr, x, y, 0);
+        return [coord.x, coord.y, coord.z];
+    }
+
+    isPointAboveHorizon(tr: Transform, p: Point): boolean {
+        return !globePointCoordinate(tr, p.x, p.y, false);
```
Comment (karimnaaji) [inline src/geo/projection/globe.js:109]: nit: Similar suggestion here to make it explicit:
```suggestion
    isPointAboveHorizon(tr: Transform, p: Point): boolean {
        const raycastOnGlobe = globePointCoordinate(tr, p.x, p.y, false);
        return !rayCastOnGlobe;
```

**Review by karimnaaji — APPROVED** [review]
Works great and nice test addition, LGTM!
