### PR TITLE
Fix Tile#positionAt

### LINKED ISSUE #1899: positionAt broken
https://github.com/mapbox/mapbox-gl-js/commit/002c69071275997886fd98aa4dbc6025eed36a86#commitcomment-15298959

> positionAt function of this class expects this.scale to be defined. Otherwise the feature tree will not work where this parameter is expected to be passed in "query feature". See line 40 of this file and feature_tree.js file radius = (params.radius || 0) * (args.tileExtent || 4096) / args.scale;

### PR DESCRIPTION
**Pull request by lucaswoj**
fixes #1899 
ref https://github.com/mapbox/mapbox-gl-js/commit/002c69071275997886fd98aa4dbc6025eed36a86#commitcomment-15298959

cc @ansis @jfirebaugh @kelvinabrokwa

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Why don't we need `sourceMaxZoom` anymore?

**Comment by lucaswoj** [comment]
As part of the layer-by-layer refactoring, we no longer create tiles with `tile.coord.z > sourceMaxZoom` so that check is now irrelevant see:

 - https://github.com/mapbox/mapbox-gl-js/blob/master/js/source/tile_pyramid.js#L230
 - https://github.com/mapbox/mapbox-gl-js/blob/master/js/source/tile_pyramid.js#L122

File: js/source/tile.js [hunk 1]
```diff
@@ -32,12 +32,12 @@ Tile.prototype = {
...
-        coord = coord.zoomTo(Math.min(this.coord.z, sourceMaxZoom));
+    positionAt: function(coord) {
+        var zoomedCoord = coord.zoomTo(this.coord.z);
         return {
-            x: (coord.column - this.coord.x) * this.tileExtent,
-            y: (coord.row - this.coord.y) * this.tileExtent,
-            scale: this.scale
+            x: (zoomedCoord.column - this.coord.x) * this.tileExtent,
+            y: (zoomedCoord.row - this.coord.y) * this.tileExtent,
+            scale: this.tileSize
```
Comment (lucaswoj) [inline js/source/tile.js]: This doesn't _seem_ right to me but matches the behavior before https://github.com/mapbox/mapbox-gl-js/commit/002c69071275997886fd98aa4dbc6025eed36a86, as verified by running the new unit tests on 6deae336507751992d4c88cd7c024d48a10e56cc

**Comment by jfirebaugh** [comment]
Ok, but [1](https://github.com/mapbox/mapbox-gl-js/blob/83d7c6796e17d1dab21f2984ec00d72ccfd0399b/js/source/tile_pyramid.js#L360-L360), [2](https://github.com/mapbox/mapbox-gl-js/blob/83d7c6796e17d1dab21f2984ec00d72ccfd0399b/js/source/tile_pyramid.js#L388-L389). Should the parameter no longer be passed?

Git history indicates this was related to supporting `featuresAt` with overzoomed tiles. Please confer with @ansis on this, and add a test for `featuresAt` with an overzoomed tile to the [query-tests](https://github.com/mapbox/mapbox-gl-test-suite/tree/master/query-tests).

**Comment by lucaswoj** [comment]
To the best of my understanding, `sourceMaxZoom`  was always unnecessary because `tile.coord.z <= sourceMaxZoom` is always true, though that might not have been obvious when the `Tile#calculateMatrices` method existed. I removed the argument from those call sites ([1](https://github.com/mapbox/mapbox-gl-js/blob/83d7c6796e17d1dab21f2984ec00d72ccfd0399b/js/source/tile_pyramid.js#L360-L360), [2](https://github.com/mapbox/mapbox-gl-js/blob/83d7c6796e17d1dab21f2984ec00d72ccfd0399b/js/source/tile_pyramid.js#L388-L389)). Does this all sound right to you, @ansis? 

I'll look at overzoomed `featuresAt` next.

**Comment by ansis** [comment]
I think we do actually create tiles with `tile.coord.z > sourceMaxZoom` because of these two sneaky lines:
- https://github.com/mapbox/mapbox-gl-js/blob/492c098b9872ab170daad46dd3fbf64cbaac35c3/js/source/tile_pyramid.js#L119
- https://github.com/mapbox/mapbox-gl-js/blob/492c098b9872ab170daad46dd3fbf64cbaac35c3/js/source/tile_coord.js#L158

so I think https://github.com/mapbox/mapbox-gl-js/pull/1909/files#diff-5de49be07285027d44a5f4cd57d7e395L36 will break overscaled tiles

**Comment by ansis** [comment]
the `tile.coord.z > sourceMaxZoom` tiles are really weird.

If `sourceMaxZoom = 14` then tile `{ z: 16, x: 1, y: 2}` is actually a `{ z: 14, x: 1, y: 2 }` tile parsed with the `z16` style.

**Comment by lucaswoj** [comment]
I misread that code. Thanks @ansis!

**Comment by lucaswoj** [comment]
@jfirebaugh @ansis I think this is ready to go now. :eyes:?

File: js/source/tile.js [hunk 2]
```diff
@@ -13,12 +13,13 @@ module.exports = Tile;
...
  * @private
  */
-function Tile(coord, size) {
+function Tile(coord, size, sourceMaxZoom) {
     this.coord = coord;
     this.uid = util.uniqueId();
     this.loaded = false;
     this.uses = 0;
     this.tileSize = size;
+    this.sourceMaxZoom = sourceMaxZoom;
```
Comment (lucaswoj) [inline js/source/tile.js]: This more-or-less resolves https://github.com/mapbox/mapbox-gl-js/issues/1912

File: js/source/tile.js [hunk 3]
```diff
@@ -32,12 +33,11 @@ Tile.prototype = {
...
      * @private
      */
-    positionAt: function(coord, sourceMaxZoom) {
-        coord = coord.zoomTo(Math.min(this.coord.z, sourceMaxZoom));
+    positionAt: function(coord) {
+        var zoomedCoord = coord.zoomTo(Math.min(this.coord.z, this.sourceMaxZoom));
         return {
-            x: (coord.column - this.coord.x) * this.tileExtent,
-            y: (coord.row - this.coord.y) * this.tileExtent,
-            scale: this.scale
```
Comment (lucaswoj) [inline js/source/tile.js]: I think it makes more sense for `TilePyramid` to calculate `scale` because the `TilePyramid` is necessarily coupled to the `Transformation` while `Tile` is not.

File: package.json [hunk 4]
```diff
@@ -37,7 +37,7 @@
     "eslint": "^1.5.0",
     "eslint-config-mourner": "^1.0.0",
     "istanbul": "^0.4.1",
-    "mapbox-gl-test-suite": "mapbox/mapbox-gl-test-suite#59361318b66e6262765974515d73bc3f32a8260b",
+    "mapbox-gl-test-suite": "mapbox/mapbox-gl-test-suite#35a6fc56d7eb023b123a432d51ff8a9dbfeaa002",
```
Comment (lucaswoj) [inline package.json]: Fixes the query tests and adds an overzoomed query test

**Comment by ansis** [comment]
Looks good to me!
