### PR TITLE
Simplify and fix cascade

### LINKED ISSUE #2357: map.addClass issue when "paint" style not visible
**mapbox-gl-js 0.16.0**:

### Steps to Trigger Behavior

 1. Run (Edited for new link) http://jsbin.com/casukehoga/1/edit?html,output and click addClass

### Expected Behavior

Water polygons shown

### Actual Behavior

Nothing shown. if you change the paint fill-opacity to 1, then adding the class works.

### PR DESCRIPTION
**Pull request by mourner**
Fixes #2357 and also a prerequisite for #2339 since it adds `Style` `updatePaintTransition` method.

I didn’t refactor classes into an array in this PR but going to hit this along with #2339.

:eyes: @lucaswoj @andrewharvey

### CODE REVIEW

File: js/style/style_layer.js [hunk 1]
```diff
@@ -180,56 +180,53 @@ StyleLayer.prototype = util.inherit(Evented, {
...
-        // Apply new declarations in all active classes
-        for (var klass in this._paintDeclarations) {
-            if (klass !== "" && !classes[klass]) continue;
-            for (var name in this._paintDeclarations[klass]) {
-                applyDeclaration(name, this._paintDeclarations[klass][name]);
-            }
+    // update all paint transitions and layout/paint constant values
+    cascade: function(classes, options, globalOptions, animationLoop) {
+        var declarations = util.extend({}, this._paintDeclarations['']);
+        for (var klass in classes) {
```
Comment (lucaswoj) [inline js/style/style_layer.js]: What guarantees do we make about the order that style classes are applied to the map? We should document this explicitly somewhere.

**Comment by lucaswoj** [comment]
🚢

File: js/style/style_layer.js (hunk 1 above)
Comment (mourner) [inline js/style/style_layer.js]: As mention in the PR description, I want to hit this in a follow-up PR.
