### PR TITLE
Fix isFeatureConstant test in Style#setPaintProperty

### LINKED ISSUE #5370: Style#setPaintProperty needs update for expressions
This code hasn't been updated for expressions and will not do the right thing if passed a feature-varying expression:

https://github.com/mapbox/mapbox-gl-js/blob/ef5e3890f6e8a54c8fb5ffa2e1c96f6a8f0234b6/src/style/style.js#L791-L796

The ad-hoc check should be replaced with a call to parse the expression and check the `isFeatureConstant` property on the result.

cc @anandthakker

### PR DESCRIPTION
**Pull request by jfirebaugh**
Fixes #5370.

### CODE REVIEW

File: src/style/style_layer.js [hunk 1]
```diff
@@ -193,7 +194,10 @@ class StyleLayer extends Evented {
         return false;
     }
 
-    updatePaintTransitions(options: any, globalOptions: any, animationLoop: any, zoomHistory: any) {
+    updatePaintTransitions(options: {transition?: boolean},
+                           globalOptions?: TransitionSpecification,
+                           animationLoop?: AnimationLoop,
+                           zoomHistory?: any) {
```
Comment (anandthakker) [inline src/style/style_layer.js]: is zoomHistory here still `any` because of the `ZoomHistory | {}` in Style?

Comment (jfirebaugh) [reply src/style/style_layer.js]: Yeah... we should fix that eventually.
