### PR TITLE
fix tile debug rendering

### LINKED ISSUE #2034: map debug setting incorrect in 0.13.x
The `.debug` option on the map object only shows a single tile outlined in 0.13, which is a regression from 0.12.x, which showed all tile boundaries when the debug option was turned on.

2016-02-01 at 12 29 pm

### PR DESCRIPTION
**Pull request by ansis**
fix #2034

- [x] add render test https://github.com/mapbox/mapbox-gl-test-suite/issues/74

### CODE REVIEW

**Comment by ansis** [comment]
@lucaswoj can you review?

File: js/render/draw_debug.js [hunk 1]
```diff
@@ -2,40 +2,53 @@
...
+    // Draw the halo with multiple 1px lines instead of one wider line because
+    // the gl spec doesn't guarantee support for lines with width > 1.
+    var tileSize = source.getTile(coord).tileSize;
+    var onePixel = EXTENT / (Math.pow(2, painter.transform.zoom - coord.z) * tileSize);
+    for (var x = -1; x <= 1; x += 2) {
+        for (var y = -1; y <= 1; y += 2) {
+            gl.setPosMatrix(mat4.translate([], posMatrix, [onePixel * x, onePixel * y, 0]));
+            gl.drawArrays(gl.LINES, 0, vertices.length / painter.debugTextBuffer.itemSize);
+        }
+    }
```
Comment (lucaswoj) [inline js/render/draw_debug.js]: :grimacing:

File: js/render/painter.js [hunk 2]
```diff
@@ -152,7 +152,7 @@ Painter.prototype.setup = function() {
     gl.bufferData(
         gl.ARRAY_BUFFER,
         new Int16Array([
-            0, 0, EXTENT - 1, 0, EXTENT - 1, EXTENT - 1, 0, EXTENT - 1, 0, 0]),
+            0, 0, EXTENT, 0, EXTENT, EXTENT, 0, EXTENT, 0, 0]),
```
Comment (lucaswoj) [inline js/render/painter.js]: Why did we have `- 1` in here before?

File: js/render/draw_debug.js [hunk 3]
```diff
@@ -2,40 +2,53 @@
...
     gl.uniform4f(shader.u_color, 1, 1, 1, 1);
-    gl.drawArrays(gl.LINES, 0, vertices.length / painter.debugTextBuffer.itemSize);
-    gl.lineWidth(2 * browser.devicePixelRatio);
+
+    // Draw the halo with multiple 1px lines instead of one wider line because
+    // the gl spec doesn't guarantee support for lines with width > 1.
+    var tileSize = source.getTile(coord).tileSize;
+    var onePixel = EXTENT / (Math.pow(2, painter.transform.zoom - coord.z) * tileSize);
+    for (var x = -1; x <= 1; x += 2) {
+        for (var y = -1; y <= 1; y += 2) {
```
Comment (lucaswoj) [inline js/render/draw_debug.js]: I think this loop would be more intuitive written as 

```js
var translations = [[-1, -1], [-1, 1], [1, -1], [1, 1]];
for (var i = 0, i < translations.length, ...
```

File: js/render/draw_debug.js (hunk 1 above)
Comment (ansis) [inline js/render/draw_debug.js]: yeah, it would be good to switch away from gl.LINES completely. Until then we can do this or not render halos. I'm not sure which is worse.

File: js/render/painter.js (hunk 2 above)
Comment (ansis) [inline js/render/painter.js]: I'm not sure. I think conceptually with the -1 the lines are always strictly within a tile's boundaries. But since gl.LINES are snapped to the nearest pixel this isn't actually useful. -native doesn't have this

With the -1 the tile boundaries sometimes overlap with neighbours (creating a 1px line) and sometimes doesn't overlap (creating a 2px line). This makes it a consistent 1px.

File: js/render/draw_debug.js (hunk 3 above)
Comment (ansis) [inline js/render/draw_debug.js]: I switched to this and pushed a new version.

**Comment by lucaswoj** [comment]
Looks good to me! :ship:
