### PR TITLE
re-add queuing for getResource calls

### LINKED ISSUE #8998: IE11 tile queue regression
Capturing @arindam1993 https://github.com/mapbox/mapbox-gl-js/pull/8913#issuecomment-553622495 to make sure we address it before doing a release:

> this PR could bring back the issue of requests being stuck in the pending state on IE11 when tile requests get cancelled, I just did some testing and it looks like it has 😬.

### PR DESCRIPTION
**Pull request by ansis**
This is alternative to https://github.com/mapbox/mapbox-gl-js/pull/9022 . It tries to fix #8998 by  reverting the relevant behavior change in #8913.

This isn't an improvement. It just tries to avoid a regression.

#8913 made all worker tasks received by the main thread execute immediately. This pr re-adds queuing for `getResource` tasks.

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [ ] post benchmark scores
 - [x] manually test the debug page

### CODE REVIEW

File: src/util/actor.js [hunk 1]
```diff
@@ -110,40 +110,42 @@ class Actor {
...
-            // In workers, store the tasks that we need to process before actually processing them. This
-            // is necessary because we want to keep receiving messages, and in particular,
-            // <cancel> messages. Some tasks may take a while in the worker thread, so before
-            // executing the next task in our queue, postMessage preempts this and <cancel>
-            // messages can be processed. We're using a MessageChannel object to get throttle the
-            // process() flow to one at a time.
-            this.tasks[id] = data;
-            this.taskQueue.push(id);
-            if (isWorker()) {
+            if (isWorker() || data.type === 'getResource') {
```
Comment (kkaefer) [inline src/util/actor.js]: Instead of hardcoding the name of the message, can we find another way of marking tasks as immedidate vs. queueable, e.g. by checking for `!data.immediate` here, and adding `immediate as another argument to `Actor#send`?

File: src/util/actor.js [hunk 2]
```diff
@@ -110,40 +110,42 @@ class Actor {
...
+            // Schedule another process call if we know there's more to process _before_ invoking the
+            // current task. This is necessary so that processing continues even if the current task
+            // doesn't execute successfully.
+            if (this.taskQueue.length) {
+                this.invoker.trigger();
+            }
+            if (!task) {
+                // If the task ID doesn't have associated task data anymore, it was canceled.
+                return;
+            }
```
Comment (kkaefer) [inline src/util/actor.js]: Let's separate this into two functions

File: src/util/actor.js (hunk 1 above)
Comment (ansis) [reply src/util/actor.js]: done in d28ac5668f35d9354b9ae1fc7dfbb15b9296aec7

File: src/util/actor.js (hunk 2 above)
Comment (ansis) [reply src/util/actor.js]: done in d28ac5668f35d9354b9ae1fc7dfbb15b9296aec7

File: src/util/actor.js [hunk 3]
```diff
@@ -53,7 +53,7 @@ class Actor {
      * @param targetMapId A particular mapId to which to send this message.
      * @private
      */
-    send(type: string, data: mixed, callback: ?Function, targetMapId: ?string): ?Cancelable {
+    send(type: string, data: mixed, callback: ?Function, targetMapId: ?string, mustQueue: ?string): ?Cancelable {
```
[the remark this answers is not in the document]
Comment (ansis) [reply src/util/actor.js]: Thanks! done in 1028521eae756ae638a02fa8ec7423e0d8cfc43d
