### PR TITLE
disable custom layers for non-mercator projections

### LINKED ISSUE #11159: Disable custom layers rendering when using non-mercator projection
This ticket is to track custom layers + non-mercator projection update for v2.6.0-final. The combination projection/custom layers is unexpected:

Screen Shot 2021-10-20 at 2 48 17 PM

For v2.6.0-final, we should:
- Skip rendering of custom layers to prevent broken behaviors
- Maybe issue a warning to mention that custom layers aren't supported when the user try to use both of them together
- Update the docs (either in the custom layers API or the spec for projection) to prevent confusion or bad impression for users trying that feature combination
- Document next steps for full support

### PR DESCRIPTION
**Pull request by ansis**
fix #11159

Disable custom layers with non-mercator projections.

Screen Shot 2021-11-02 at 4 13 28 PM

### CODE REVIEW

**Review by mourner — APPROVED** [review]

File: src/render/draw_custom.js [hunk 1]
```diff
@@ -14,6 +15,11 @@ function drawCustom(painter: Painter, sourceCache: SourceCache, layer: CustomSty
     const context = painter.context;
     const implementation = layer.implementation;
 
+    if (painter.transform.projection.name !== 'mercator') {
+        warnOnce('Custom layers are not yet supported with non-mercator projections. Use mercator to enable custom layers.');
+        return;
+    }
```
Comment (karimnaaji) [inline src/render/draw_custom.js:21]: This seems also worth noting in the docs of custom layers.

**Review by karimnaaji — APPROVED** [review]
