### PR TITLE
make sure icons fit before the ends of the line

### LINKED ISSUE #2062: oneway arrows going in the wrong direction
screen shot 2016-02-04 at 1 16 48 pm

I think this is happening near tile edges.

http://localhost:9966/debug/#16.1/38.90339/-77.03731

https://github.com/mapbox/mapbox-gl-js/pull/1980 might fix this.

### PR DESCRIPTION
**Pull request by ansis**
fixes #2062

This skips anchors if there is not enough room before the end of the line for the icon to fit.

Previously it allowed icons that extended past the end of a line as long as the icon's anchor fit on the line. This changes it so that the icon itself has to fit on the line. With these changes there are no icons on really short lines and no icons right at the end of lines.

The test suite changes (https://github.com/mapbox/mapbox-gl-test-suite/commit/6b6a03ebe8c106db1a85e88572293e523c71ba72) make it look like this is a huge change, but in actual maps it only drops a small number of icons that are right at the ends of lines or are on really short lines.

#2062 would also be fixed by https://github.com/mapbox/mapbox-gl-js/issues/2067 (which we should still do).

:eyes: @lucaswoj @jfirebaugh

### CODE REVIEW

File: js/symbol/get_anchors.js [hunk 1]
```diff
@@ -68,7 +74,9 @@ function resample(line, offset, spacing, angleWindowSize, maxAngle, labelLength,
                 x = interpolate(a.x, b.x, t),
                 y = interpolate(a.y, b.y, t);
 
-            if (x >= 0 && x < tileExtent && y >= 0 && y < tileExtent) {
+            if (x >= 0 && x < tileExtent && y >= 0 && y < tileExtent &&
+                    markedDistance - halfLabelLength >= 0 &&
+                    markedDistance + halfLabelLength <= lineLength) {
```
Comment (lucaswoj) [inline js/symbol/get_anchors.js]: This statement could use some more documentation, either in the form of a `// comment` or factored out subexpressions

Comment (ansis) [inline js/symbol/get_anchors.js]: added comment f914a34

**Comment by lucaswoj** [comment]
This looks good to me.
