### PR TITLE
Fix easeTo pan, zoom, and rotate when initial rotation != 0

### LINKED ISSUE #1944: easeTo does not work properly if multiple values are changed
I created a small jsfiddle to explain the issue. 
https://jsfiddle.net/rzgqmjj0/1/

If you press the "target" button in the upper left corner the camera flies to the correct position, but if you press the start button afterwards you don't return to the initial position. To get to the initial position, you have to click "start" a second time.

This error only occurs if more than one value (zoom, bearing or pitch) is changed at the same time.

### PR DESCRIPTION
**Pull request by lucaswoj**
fixes #1944 

This fixes the bug but might not be the most elegant solution.

:eyes: :thought_balloon: @mourner @ansis @1ec5

### CODE REVIEW

File: js/ui/camera.js [hunk 1]
```diff
@@ -475,10 +475,6 @@ util.extend(Camera.prototype, /** @lends Map.prototype */{
             this.pitching = true;
         }
 
-        if (this.zooming && !around) {
-            around = tr.pointLocation(tr.centerPoint.add(to.sub(from).div(1 - 1 / scale)));
-        }
```
Comment (lucaswoj) [inline js/ui/camera.js]: As far as I can tell, this code is not needed. There may also be a solution that involves incorporating bearing into the above calculation.

File: js/ui/camera.js [hunk 2]
```diff
@@ -475,10 +475,6 @@ util.extend(Camera.prototype, /** @lends Map.prototype */{
...
-
```
Comment (1ec5) [inline js/ui/camera.js]: Removing this makes sense. :+1: It was preventing the else statement below from ever being reached when the zooming option was specified, and only that else branch knows how to pan.

In the gl-native implementation, `anchor` is applied after `center`, not instead of `center`, and `anchor` has no default value.

**Comment by mourner** [comment]
:+1: the removed code was apparently needed earlier but is not needed after some more recent changes, might be worth looking in git blame.

**Comment by lucaswoj** [comment]
I'm 90% sure that the "more recent changes" were done by me but I can't find the commit off hand.
