### PR TITLE
Fix feature-dependent `config` expressions

### LINKED ISSUE #13452: Multiple issues wrt. feature-dependent `config` expressions
I'd like to have `config` properties that are expressions. I'd also like those expressions to be able to use feature properties, like so:

```json
{
  "schema": {
    "room-color": {
      "type": "color",
      "default": ["case", ["==", ["get", "room-type"], "administrative"], "red", "blue"]
    }
  },
  "layers": [
    "id": "rooms-fill",
    "type": "fill",
    "paint": {
      "fill-color": ["config", "room-color"]
    }
  ]
}
```

This is only partly supported ATM, because of (at least) two issues I bumped into while stepping through the evaluation code path in one of the workers:

1. The expression assigned to `fill-color` above is considered feature constant, and so feature data is not loaded during evaluation. This can be hacked around by wrapping the whole thing into e.g. a `let` with a `get` – but this is suboptimal (think `["let", "_" ["get", "room-type"], ["config", "room-color"]]`).

2. Evaluating a `match` expression in the worker fails and defaults to the "otherwise" branch, if the expression being evaluated is a config expression. This happens [here](https://github.com/mapbox/mapbox-gl-js/blob/87938fb284bf9f2c4b1bbbc7baaad074438ae014/src/style-spec/expression/definitions/match.ts#L102) as the `typeOf(input) === this.inputType` check returns `false`, probably because the [type constants](https://github.com/mapbox/mapbox-gl-js/blob/main/src/style-spec/expression/types.ts#L48-L58) in the worker are not referentially the same as the `{kind: ...}` value from the unserialized version of the config expression from the main thread(?).

**mapbox-gl-js version**: 3.11.0

**browser**: Arc

### Link to Demonstration

https://codesandbox.io/p/sandbox/lxfnlg?file=%2Findex.html%3A39%2C20

(If both of these issues are fixed, one of the squares should be red.)

### PR DESCRIPTION
**Pull request by brncsk**
This PR aims to fix #13452.

Some remarks:

- A more roboust alternative to `typeEquals` would be to ensure that the [type constants](https://github.com/mapbox/mapbox-gl-js/blob/main/src/style-spec/expression/types.ts#L48-L58) maintain their identity across the `postMessage` boundary, but that would be a more involved refactor than what I could do.

- An alternative to the `featureConstant` flag in `Config` would be to store the config expression itself in the instance, and defer to `eachChild` for determining whether it's feature constant, however I'm not sure that'd work (can the value of a config option change between parsing and evaluating the `["config"]` expression)?

## Launch Checklist

 - [x] Make sure the PR title is descriptive and preferably reflects the change from the user's perspective.
 - [ ] Add additional detail and context in the PR description (with screenshots/videos if there are visual changes).
 - [x] Manually test the debug page.
 - [x] Write tests for all new functionality and make sure the CI checks pass.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores if the change could affect performance.
 - [ ] Tag `@mapbox/map-design-team` `@mapbox/static-apis` if this PR includes style spec API or visual changes.
 - [ ] Tag `@mapbox/gl-native` if this PR includes shader changes or needs a native port.

### CODE REVIEW

File: src/style-spec/expression/definitions/config.ts [hunk 1]
```diff
@@ -130,7 +150,7 @@ class Config implements Expression {
     serialize(): SerializedExpression {
         const res = ["config", this.key];
         if (this.scope) {
-            res.concat(this.key);
+            res.concat(this.scope);
```
Comment (stepankuzmin) [inline src/style-spec/expression/definitions/config.ts:153]: Good catch!

**Review by stepankuzmin — APPROVED** [review]
Hey @brncsk! Thank you for the great contribution! I'm really sorry it took me a bit longer to review it. I appreciate your patience!
