### PR TITLE
Fix for webgl-based canvas sources rendering flipped in 0.40.0 + non-animated optimization

### LINKED ISSUE #5300: CanvasSource coordinates inverted in 0.40.0
**mapbox-gl-js version**: 0.40.0

### Steps to Trigger Behavior

 1. Add canvas layer to map with coordinates order top left, top right, bottom right, bottom left per [spec](https://www.mapbox.com/mapbox-gl-js/style-spec/#sources-canvas).

### Expected Behavior

Canvas layer should render in desired location.

### Actual Behavior

Canvas layer is rotated and flipped. If you use the following order the canvas layer will render correctly: bottom left, bottom right, top right, top left.

Here's a giphy that compares v0.37.0 (first, smooth fps) to v0.40.0 (second, choppy fps). Notice the colored layer is positioned differently in the second example.

Framerate issues addressed here: https://github.com/mapbox/mapbox-gl-js/issues/5301

### PR DESCRIPTION
**Pull request by lbud**
WebGL APIs and Canvas APIs are vertically flipped (gl reads from the lower left, canvas from the upper left), so I introduced https://github.com/mapbox/mapbox-gl-js/issues/5300 in #5155. Eventually we should try to write render tests with a secondary webgl canvas 🤔 to catch bugs like this, but in the meantime this should make it into the 0.40.1 patch release.

Edit: this PR also modifies the intermediary read step to only reread if a canvas is supposed to be animated, if it hasn't been read yet, or if it is resized, to mitigate performance concerns for non-animated canvases (see https://github.com/mapbox/mapbox-gl-js/issues/5301).

Fixes #5300.
Refs #5301.

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] manually test the debug page

### CODE REVIEW

File: src/source/canvas_source.js [hunk 1]
```diff
@@ -127,7 +127,11 @@ class CanvasSource extends ImageSource {
             gl.readPixels(0, 0, this.width, this.height, gl.RGBA, gl.UNSIGNED_BYTE, data);
             if (!this.secondaryContext) this.secondaryContext = window.document.createElement('canvas').getContext('2d');
             const imageData = this.secondaryContext.createImageData(this.width, this.height);
-            imageData.data.set(data);
+            const flipped = new Uint8Array(this.width * this.height * 4);
+            for (let i = this.height - 1, j = 0; i >= 0; i--, j++) {
+                flipped.set(data.slice(i * this.width * 4, (i + 1) * this.width * 4), j * this.width * 4);
```
Comment (mourner) [inline src/source/canvas_source.js]: I'd suggest avoiding many `slice` operations since they create a new array every time. 4 lines setting each of the 4 values of the array will be faster.

Comment (ansis) [reply src/source/canvas_source.js]: The array looks like its an entire row, not just four values. It might make sense to try `data.subarray(begin, end)` which is like `.slice()` except it provides a view into the existing array without copying it.

Comment (mourner) [reply src/source/canvas_source.js]: Oh, you're right. In that case a secondary inner loop might get also work well.

Comment (lbud) [reply src/source/canvas_source.js]: Oh cool, did not know about `subarray` — thanks @ansis @mourner. (I tried the secondary loop in this test as well for good measure: )
image

File: src/source/canvas_source.js [hunk 2]
```diff
@@ -114,21 +115,29 @@ class CanvasSource extends ImageSource {
...
+            if (!this.canvasData || resize) {
+                this.canvasData = this.secondaryContext.createImageData(this.width, this.height);
+            }
+
+            // WebGL reads pixels bottom to top, but for our ImageData object we need top to bottom: flip here
+            const flipped = new Uint8Array(this.width * this.height * 4);
+            for (let i = this.height - 1, j = 0; i >= 0; i--, j++) {
+                flipped.set(data.subarray(i * this.width * 4, (i + 1) * this.width * 4), j * this.width * 4);
+            }
+            this.canvasData.data.set(flipped);
```
Comment (mourner) [inline src/source/canvas_source.js]: One more thing — is it possible to do `this.canvasData.data.set` inside the loop instead of using a temporary `flipped` array?
