### PR TITLE
Only evaluate CrossFaded properties at integer zooms

### LINKED ISSUE #6390: Incorrect cross-fading at non-integer zoom levels
http://jsbin.com/gatejucoti/edit?html,output

crossfade

This is because the crossfade interpolation factor `t`  is designed to cross-fade the property across integer zoom levels, so when you have a non-integer zoom level, the `from` and `to` values of the `CrossFadedProperty` will be incorrect at integer zooms after a non-integer stop. 

I think we should disallow non-integer stops for these properties, because they're non-interpolatable so they won't work anyways with data-driven expressions, so I think it may cause confusion if they're supported for camera expressions. 

@nickidlugash @natslaughter do you have strong feelings about this?

cc @ansis @anandthakker

### PR DESCRIPTION
**Pull request by mollymerp**
fixes #6390 

⚠️ this might be a breaking change for some people even though it is also a bug fix

question: should we have a style spec field that indicates if the property is cross-faded or not to avoid having to hard code the property name string check?

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] write tests for all new functionality
 - [x] document any changes to public APIs
 - [ ] post benchmark scores
 - [x] manually test the debug page

### CODE REVIEW

File: src/style-spec/validate/validate_expression.js [hunk 1]
```diff
@@ -18,5 +18,12 @@ export default function validateExpression(options: any) {
         return [new ValidationError(options.key, options.value, 'Invalid data expression for "text-font". Output values must be contained as literals within the expression.')];
     }
 
+    if (options.expressionContext === 'property' && expression.value.kind === 'camera' && options.propertyKey.match(/(-pattern)|(-dasharray)/)) {
```
Comment (ansis) [inline src/style-spec/validate/validate_expression.js]: Would it be slightly clearer to explicitly list all the properties this applies to instead of using a regular expression?

Comment (jfirebaugh) [reply src/style-spec/validate/validate_expression.js]: It's another case where #6389 (specifically https://github.com/mapbox/mapbox-gl-js/issues/6389#issuecomment-376245679) would help.

**Comment by jfirebaugh** [comment]
I'm slightly worried about the consequences of changing this. We had at least one case where we made validation stricter in a similar area and later had to roll it back because existing styles stopped working (https://github.com/mapbox/mapbox-gl-style-spec/pull/413).

**Comment by anandthakker** [comment]
> then we also can (and, I think, should) address this by making sure that in CrossFadedProperty#possiblyEvaluate, we only evaluate the expression at integer zoom levels

@mollymerp is the above correct?  If so, and we want to avoid risking breaking existing styles, we could just do that instead.

File: src/style-spec/reference/v8.json [hunk 2]
```diff
@@ -2965,7 +2965,7 @@
       "function": "piecewise-constant",
       "zoom-function": true,
       "transition": true,
-      "doc": "Name of image in sprite to use for drawing images on extruded fills. For seamless patterns, image width and height must be a factor of two (2, 4, 8, ..., 512).",
+      "doc": "Name of image in sprite to use for drawing images on extruded fills. For seamless patterns, image width and height must be a factor of two (2, 4, 8, ..., 512). Note that this property does not support zoom-dependent expressions with non-integer zoom inputs.",
```
[the remark this answers is not in the document]
Comment (mollymerp) [reply src/style-spec/reference/v8.json]: 👍 yep that's more concise.
