### PR TITLE
guard for offset edgecase in flyTo

### LINKED ISSUE #5322: failed to invert matrix
I get this error. I see other issues relating to using fitbounds, but it looks more like this is triggered by zooming in/out. The chrome browser completely hangs on it and needs restarting.

I am on mapbox-gl-js 0.40.0
```
Uncaught Error: failed to invert matrix
    at Transform._calcMatrices (mapbox-gl.js?d5ed:123)
    at Transform.prototypeAccessors.zoom.set (mapbox-gl.js?d5ed:123)
    at eval (mapbox-gl.js?d5ed:366)
    at eval (mapbox-gl.js?d5ed:366)
    at a (mapbox-gl.js?d5ed:408)
Transform._calcMatrices @ mapbox-gl.js?d5ed:123
prototypeAccessors.zoom.set @ mapbox-gl.js?d5ed:123
(anonymous) @ mapbox-gl.js?d5ed:366
(anonymous) @ mapbox-gl.js?d5ed:366
a @ mapbox-gl.js?d5ed:408
requestAnimationFrame (async)
timed @ mapbox-gl.js?d5ed:408
e._ease @ mapbox-gl.js?d5ed:366
e.flyTo @ mapbox-gl.js?d5ed:366
(anonymous) @ util.js?93ee:311
setTimeout (async)
postMarker @ util.js?93ee:310
Evented.fire @ mapbox-gl.js?d5ed:424
e._easeToEnd @ mapbox-gl.js?d5ed:366
(anonymous) @ mapbox-gl.js?d5ed:366
e._finishEase @ mapbox-gl.js?d5ed:366
(anonymous) @ mapbox-gl.js?d5ed:366
a @ mapbox-gl.js?d5ed:408
requestAnimationFrame (async)
a @ mapbox-gl.js?d5ed:408
requestAnimationFrame (async)
a @ mapbox-gl.js?d5ed:408
requestAnimationFrame (async)
a @ mapbox-gl.js?d5ed:408
requestAnimationFrame (async)
a @ mapbox-gl.js?d5ed:408
requestAnimationFrame (async)
a @ mapbox-gl.js?d5ed:408
```

### PR DESCRIPTION
**Pull request by mollymerp**
fix #5322 

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] write tests for all new functionality
 - [ ] document any changes to public APIs
 - [ ] post benchmark scores
 - [x] manually test the debug page

### CODE REVIEW

File: src/ui/camera.js [hunk 1]
```diff
@@ -785,7 +785,7 @@ class Camera extends Evented {
         let S = (r(1) - r0) / rho;
 
         // When u₀ = u₁, the optimal path doesn’t require both ascent and descent.
-        if (Math.abs(u1) < 0.000001 || isNaN(S)) {
+        if (Math.abs(u1) < 0.000001 || isNaN(S) || S === Infinity) {
```
Comment (mourner) [inline src/ui/camera.js]: `!isFinite(S)` could be better here since it also caches `-Infinity`.
