### PR TITLE
Fix some failed results from Web map tools WCAG 2.1 evaluation

### LINKED ISSUE #3959: make AttributionControl with compact option accessible
**mapbox-gl-js version**: 0.31.0

As far as I can tell, there is no way to activate a compacted attribution control using only the keyboard. The compacted (i) should act more like a button that can get focus by tabbing and expanding using enter.

### PR DESCRIPTION
**Pull request by tristen**
Addresses some Level A and Level AA failures as outlined in https://github.com/Malvoz/web-maps-wcag-evaluation/blob/ac797a3e5fe984db27662c27ae05077e7b22026b/README.md

### Level A

In https://github.com/Malvoz/web-maps-wcag-evaluation#131-info-and-relationships-level-a

> The "Zoom out" control's disabled state cannot be programmatically determined.

| Change | Screenshot |
| --- | --- |
| Adds `aria-hidden` attribute when min/max controls trigger disabled states | disabled-state |

In https://github.com/Malvoz/web-maps-wcag-evaluation#211-keyboard-level-a

> Control to display attribution and feedback links is not keyboard accessible.

| Change | Screenshot |
| --- | --- |
| When attribution is compact, the icon now acts as a toggle button to open and close attribution contents. This changes the behavior of it being triggered on hover but I think its a more sensible/predictable change to make. | attribution |

In https://github.com/Malvoz/web-maps-wcag-evaluation#412-name-role-value-level-a

> The "map component" (<canvas tabindex="0">, which acts as a control to both zoom and pan the map display) is missing role.

Added `role:region` to the canvas container.

> Control to display attribution and feedback links is missing name and role.

Added `role:list` to the `.mapboxgl-ctrl-attrib-inner` container. This also requires an upstream change to the TileJSON doc to add [`role:listitem`](https://www.w3.org/TR/wai-aria-1.1/#listitem)

### Level AA

In https://github.com/Malvoz/web-maps-wcag-evaluation#247-focus-visible-level-aa

> 1 tab stop without focus indicator.

This is addressed by turning the compact attribution link into a button toggle with focus.

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] include before/after visuals or gifs if this PR includes visual changes
 - [x] write tests for all new functionality
 - [ ] ~~document any changes to public APIs~~
 - [ ] ~~post benchmark scores~~
 - [x] manually test the debug page
 - [ ] ~~tagged `@mapbox/map-design-team` `@mapbox/static-apis` if this PR includes style spec API or visual changes~~
 - [ ] ~~tagged `@mapbox/gl-native` if this PR includes shader changes or needs a native port~~
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [x] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog>Addresses some Level A and Level AA accesibility recommendations</changelog>`

---

- Closes #3959

### CODE REVIEW

**Comment by ryanhamley** [comment]
That's a really cool doc that we can reference! This is exciting work.

@tristen would you be willing to take a look at https://github.com/mapbox/mapbox-gl-js/pull/9774 as part of this work? It's an attempt to make markers more accessible and focusable. I'm not sure it's quite ready, but it would be helpful to get a second set of eyes on it.

Also cc @malwoodsantoro who has been working on an accessibility plugin

File: src/ui/map.js [hunk 1]
```diff
@@ -2289,6 +2289,7 @@ class Map extends Camera {
         this._canvas.addEventListener('webglcontextrestored', this._contextRestored, false);
         this._canvas.setAttribute('tabindex', '0');
         this._canvas.setAttribute('aria-label', 'Map');
+        this._canvas.setAttribute('role', 'application');
```
Comment (Malvoz) [inline src/ui/map.js:2292]: The `application` role has some unique implications for users of assistive technology that you may or may not be familiar with, or otherwise have considered:

https://www.w3.org/TR/wai-aria/#application:

> When there is a need to create an element with an interaction model that is not supported by any of the WAI-ARIA _widget_ roles, authors **_MAY_** give that element role `application`. And, when a user navigates into an element with role `application`, assistive technologies that intercept standard input events **_SHOULD_** switch to a mode that passes most or all standard input events through to the web application.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Application_Role:

> ATs intercept almost all keyboard input and consume it themselves, letting nothing through to the browser or other user agent. To be able to interact with a web page, a standard set of widgets is recognized that, when pressing a certain key (usually the <kbd>Enter</kbd> key) this mode is switched off. The screen reader mode, often called _forms mode_ or _focus mode_, lets all keyboard input go through to the browser again. <kbd>Escape</kbd> is the most common way of switching back to _browse_ mode.
>
> The application role is designed to provide a means for widgets that are not part of the standard set to be accessible for direct interaction in ATs that use both browse and focus modes for interacting with web content.

> The <kbd>tab</kbd>, <kbd>Space</kbd> and <kbd>Enter</kbd> keys, as well as <kbd>Escape</kbd> , must be handled by the application.

Additional informative article: https://www.marcozehe.de/if-you-use-the-wai-aria-role-application-please-do-so-wisely/.

For the Maps for HTML Community Group's `<mapml-viewer>` custom component (which uses Leaflet), we chose [`region`](https://www.w3.org/TR/wai-aria-1.1/#region) instead (https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/151), because it is generic enough, in terms of ARIA roles, and doesn't change the standard behavior in conjunction to screen readers.

Comment (Malvoz) [inline src/ui/map.js:2292]: The `application` role has some unique implications for users of assistive technology that you may or may not be familiar with, or otherwise have considered:

https://www.w3.org/TR/wai-aria/#application:

> When there is a need to create an element with an interaction model that is not supported by any of the WAI-ARIA _widget_ roles, authors **_MAY_** give that element role `application`. And, when a user navigates into an element with role `application`, assistive technologies that intercept standard input events **_SHOULD_** switch to a mode that passes most or all standard input events through to the web application.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Application_Role:

> ATs intercept almost all keyboard input and consume it themselves, letting nothing through to the browser or other user agent. To be able to interact with a web page, a standard set of widgets is recognized that, when pressing a certain key (usually the <kbd>Enter</kbd> key) this mode is switched off. The screen reader mode, often called _forms mode_ or _focus mode_, lets all keyboard input go through to the browser again. <kbd>Escape</kbd> is the most common way of switching back to _browse_ mode.
>
> The application role is designed to provide a means for widgets that are not part of the standard set to be accessible for direct interaction in ATs that use both browse and focus modes for interacting with web content.

> The <kbd>tab</kbd>, <kbd>Space</kbd> and <kbd>Enter</kbd> keys, as well as <kbd>Escape</kbd> , must be handled by the application.

Additional informative article: https://www.marcozehe.de/if-you-use-the-wai-aria-role-application-please-do-so-wisely/.

For the Maps for HTML Community Group's `<mapml-viewer>` custom component (which uses Leaflet), we chose [`region`](https://www.w3.org/TR/wai-aria-1.1/#region) instead (https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/151), because it is generic enough, in terms of ARIA roles, and doesn't change the standard behavior in conjunction to screen readers.

File: src/ui/control/attribution_control.js [hunk 2]
```diff
@@ -53,7 +54,12 @@ class AttributionControl {
 
         this._map = map;
         this._container = DOM.create('div', 'mapboxgl-ctrl mapboxgl-ctrl-attrib');
+        this._compactButton = DOM.create('button', 'mapboxgl-ctrl-attrib-button', this._container);
+        this._compactButton.addEventListener('click', this._toggleAttribution);
+        this._setButtonTitle(this._compactButton, 'ToggleAttribution');
+        this._compactButton.setAttribute('role', 'button');
```
Comment (Malvoz) [inline src/ui/control/attribution_control.js:60]: This seems redundant as `<button>` elements have an [implicit `role` of `button`](https://www.w3.org/TR/html-aria/#el-button).

File: src/ui/control/navigation_control.js [hunk 3]
```diff
@@ -129,6 +133,7 @@ class NavigationControl {
     _createButton(className: string, fn: () => mixed) {
         const a = DOM.create('button', className, this._container);
         a.type = 'button';
+        a.setAttribute('role', 'button');
```
Comment (Malvoz) [inline src/ui/control/navigation_control.js:136]: This seems redundant as `<button>` elements have an [implicit `role` of `button`](https://www.w3.org/TR/html-aria/#el-button).

File: src/ui/map.js (hunk 1 above)
Comment (tristen) [reply src/ui/map.js:2292]: Thanks for those details @Malvoz and that article you linked was particularly helpful. `region` sounds reasonable to use instead 👍

File: src/ui/control/attribution_control.js [hunk 4]
```diff
@@ -86,16 +92,32 @@ class AttributionControl {
...
             editLink = this._editLink = (this._container.querySelector('.mapbox-improve-map'): any);
         }
 
         const params = [
-            {key: "owner", value: this.styleOwner},
-            {key: "id", value: this.styleId},
-            {key: "access_token", value: this._map._requestManager._customAccessToken || config.ACCESS_TOKEN}
+            {key: 'owner', value: this.styleOwner},
+            {key: 'id', value: this.styleId},
+            {key: 'access_token', value: this._map._requestManager._customAccessToken || config.ACCESS_TOKEN}
```
Comment (tristen) [inline src/ui/control/attribution_control.js:120]: Not a necessary change but I just came across this string inconsistency.

**Comment by andrewharvey** [comment]
Cool looks like this would close #3959

File: src/css/mapbox-gl.css [hunk 5]
```diff
@@ -440,35 +441,30 @@ a.mapboxgl-ctrl-logo.mapboxgl-compact {
...
         display: none;
     }
 
-    .mapboxgl-ctrl-attrib.mapboxgl-compact:hover .mapboxgl-ctrl-attrib-inner {
-        display: block;
-    }
-
-    .mapboxgl-ctrl-attrib.mapboxgl-compact::after {
-        content: '';
+    .mapboxgl-ctrl-attrib-button {
```
Comment (ryanhamley) [inline src/css/mapbox-gl.css:466]: Screen Shot 2020-10-01 at 11 44 03 AM

I think the compact attribution could use a bit more space between the text and the button. When the button is focused, which it is when the control is first maximized after clicking it or hitting Enter, the blue focus ring abuts the text pretty tightly.

**Review by ryanhamley — CHANGES_REQUESTED** [review]
Overall this looks really great. I just have a few minor suggestions.

File: src/ui/control/navigation_control.js [hunk 6]
```diff
@@ -77,8 +77,12 @@ class NavigationControl {
 
     _updateZoomButtons() {
         const zoom = this._map.getZoom();
-        this._zoomInButton.disabled = zoom === this._map.getMaxZoom();
-        this._zoomOutButton.disabled = zoom === this._map.getMinZoom();
+        const isMax = zoom === this._map.getMaxZoom();
+        const isMin = zoom === this._map.getMinZoom();
+        this._zoomInButton.disabled = isMax;
+        this._zoomOutButton.disabled = isMin;
+        this._zoomInButton.setAttribute('aria-disabled', isMax ? 'true' : 'false');
```
[the remark this answers is not in the document]
Comment (tristen) [reply src/ui/control/navigation_control.js:84]: oh yeah, I originally had it like this but I was getting this error from tests:

Screen Shot 2020-09-18 at 2 26 14 PM

File: src/ui/control/attribution_control.js [hunk 7]
```diff
@@ -53,7 +55,11 @@ class AttributionControl {
 
         this._map = map;
         this._container = DOM.create('div', 'mapboxgl-ctrl mapboxgl-ctrl-attrib');
+        this._compactButton = DOM.create('button', 'mapboxgl-ctrl-attrib-button', this._container);
+        this._compactButton.addEventListener('click', this._toggleAttribution);
+        this._setElementTitle(this._compactButton, 'ToggleAttribution');
         this._innerContainer = DOM.create('div', 'mapboxgl-ctrl-attrib-inner', this._container);
+        this._innerContainer.setAttribute('role', 'list');
```
[the remark this answers is not in the document]
Comment (tristen) [reply src/ui/control/attribution_control.js:62]: Yeah, `name` and `role` for the feedback links themselves. I have a PR in a branch to address that in the TileJSON. The attribution control just receives these as strings and [appends them in](https://github.com/mapbox/mapbox-gl-js/blob/5eb9ff9b992e42678e4ac58dfba5a183fb5b3b08/src/ui/control/attribution_control.js#L193) so it felt right to do it upstream.

File: src/css/mapbox-gl.css (hunk 5 above)
Comment (tristen) [reply src/css/mapbox-gl.css:466]: Increased padding in https://github.com/mapbox/mapbox-gl-js/pull/9991/commits/67282f40d3cef6a69b4f548ae2163c4df69cb45d to address this!

Screen Shot 2020-10-04 at 1 27 37 PM

File: src/ui/control/navigation_control.js (hunk 6 above)
[the remark this answers is not in the document]
Comment (ryanhamley) [reply src/ui/control/navigation_control.js:84]: Ah, that stinks. It looks like Flow is [forcing the value supplied to `setAttribute` to be a string](https://github.com/facebook/flow/blob/v0.111.3/lib/dom.js#L1514), even though the browser implementation doesn't require that. I'd suggest changing this to `isMax.toString()` as a more concise way of writing the conversion.

**Review by ryanhamley — APPROVED** [review]
