### PR TITLE
Fix ImageSource breaking in FF/Safari if it's not immediately displayed

### LINKED ISSUE #10685: Image source content is not loaded properly if not utilized 'quickly enough' on Safari/FF
**mapbox-gl-js version**:
1.13.1 -> 2.2.0 (latest)

**browser**
Safari/Firefox (Mac OS's only: IOS/macOS/etc)
 
### Description
When adding a new 'Image' source to the map there appears to be a loading/timing issue with the initialization of the underlying content that prevents the image content from ever being displayed unless it is utilized somewhat 'immediately'.
This means that it appears to require that the source be referenced by a 'Raster' layer that is currently 'visible'.

It almost looks like an extension or regression of an earlier issue in Dec 2020: ImageSource not working in FF/Safari (#10230).

### Steps to Trigger Behavior
Repro scenario 1: 
An 'Image' source and corresponding 'Raster' layer are added to the map in quick succession but the layer's visibility layout property is set to 'none'. The underlying content will then never be displayed in this case even if the visibility property is later toggled to 'visible'

Repro scenario 2:
An 'Image' source is added to the map. Then at some point later a layer is added that references the source and is either initialized with the visibility layout property set to true or leaves it unset (true is the default).
Similarly, the content is never displayed on the map, however this shows that the loading problem is disjointed from the referencing layer and suggests some kind of timing issue where the source content has to be 'used' by some time period. 

### Console Logs
There are no warnings/errors within the console log and a cursory inspection of the map style state suggests that the map thinks everything is 'ok'. I.e SourceCache and linked Source properties within the map instance indicate that they believe the themselves to be 'loaded' (though I am not an expert on the internal structures of the library)   

### Workaround
I discovered that this issue is bypassed by way of the utilizing the 'raster-opacity' paint property as the means by which to show/hide the layer instead of the layout 'visibility' property. I'm not familiar enough with the implementation to know the implications of this finding.
For my particular scenario, this workaround is a valid and simple approach as my usage of 'raster-opacity' property is simplistic (0 or 1). However, this could become tricky if someone required more complex logic or expressions for this property.

### PR DESCRIPTION
**Pull request by mourner**
Closes #10685 by immediately decoding an image of an `ImageSource` on load for use later so that we don't hit a race condition where the memory for it is freed preemptively.

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [ ] write tests for all new functionality
 - [x] manually test the debug page
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [x] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog>Fix ImageSource breaking in FF/Safari if it's not immediately visible.</changelog>`

### CODE REVIEW

File: src/source/image_source.js [hunk 1]
```diff
@@ -78,7 +79,7 @@ class ImageSource extends Evented implements Source {
     dispatcher: Dispatcher;
     map: Map;
     texture: Texture | null;
-    image: HTMLImageElement | ImageBitmap;
+    image: ImageData;
```
Comment (rreusser) [inline src/source/image_source.js:82]: Question: Makes perfect sense. Just out of curiosity, as far as flow goes, is `ImageData | null` just not worth the trouble in this case?

**Review by rreusser — APPROVED** [review]
LGTM 👍

File: src/source/image_source.js (hunk 1 above)
Comment (mourner) [reply src/source/image_source.js:82]: I just didn't change the status quo in this particular PR, but we do need to make a sweep to clean this up — sloppy typing like this is everywhere both in this class and all over the codebase, and Flow isn't complaining. :(
