### PR TITLE
fix race condition between caching and aborting

### LINKED ISSUE #8470: Regression: unbounded memory growth on the worker side since v1.1.0
**mapbox-gl-js version**: v1.1.0
**browser**: Chrome

### Steps to Trigger Behavior

 1. Browse a simple map (e.g. `/debug`), quickly zooming back and forth.
 2. Watch workers memory footprint in the "Memory" tab.

### Expected Behavior

Memory fluctuates around a certain size.

### Actual Behavior

Memory grows indefinitely.

Since v1.1.0, quick map browsing introduces some race condition that makes some tiles to be retain on the worker side in `this.loaded` object of `VectorTileWorkerSource` indefinitely. You can track this by setting `mapboxgl.workerCount = 1`, setting Map `maxTileCacheSize` to `1`, and adding `console.log(Object.keys(this.loaded).length)` after `this.loaded[uid] = workerTile` in `vector_tile_worker_source.js`.

I bisected this down to #8363 @ansis — something in there introduced a race condition with worker cache clearing logic. Let's investigate further.

### PR DESCRIPTION
**Pull request by ansis**
If a request was aborted while it was checking the cache the request would still complete leading to a parsed tile that would never get cleared. The fix is to not call back when the request is aborted.

fix #8470

Any idea if I should / how I could add a test for this?

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [ ] write tests for all new functionality
 - [x] manually test the debug page

### CODE REVIEW

File: src/util/ajax.js [hunk 1]
```diff
@@ -172,6 +176,7 @@ function makeFetchRequest(requestParameters: RequestParameters, callback: Respon
     }
 
     return { cancel: () => {
+        aborted = true;
         if (!complete) controller.abort();
```
Comment (asheemmamoowala) [inline src/util/ajax.js]: Can't the controller's abort signal be used directly to reject or escape from `validateOrFetch` early instead of using an additional `aborted` variable?

Comment (ansis) [reply src/util/ajax.js]: from discussion in chat: let's leave this for now
