### PR TITLE
Fix bug causing worker-initiated messages to be broadcast to every map instance

### LINKED ISSUE #3086: Fix bug causing garbled text rendering when multiple maps are rendered on the page
**0.23.0**

 I've upgraded from 0.18.0.

This is a larger GWT application that uses JsInterop, so it's difficult for me to provide code to run. Before I isolate and try to reproduce this error with plain JS, it would be good to know if this is a known issue.

Ultimately all I do is use several instance of Map on the same DOM, and attach/detach them frequently. When the first instance of Map renders, it looks fine. When I detach the first instance and create and attach a second (and probably other) instance(s) of a Map, this second instance has broken rendering of text labels.

See the attached screenshot.

The code is unchanged except for some necessary API adjustments with handling GeoJSON sources.
screen shot 2016-08-27 at 22 13 24

### PR DESCRIPTION
**Pull request by anandthakker**
Closes #3086

### CODE REVIEW

**Comment by anandthakker** [comment]
@jfirebaugh This should fix it.  Confirmed it with a quick check using jsfiddle example linked in the issue.

File: js/source/worker.js [hunk 1]
```diff
@@ -148,7 +148,16 @@ util.extend(Worker.prototype, {
...
             };
-            this.workerSources[mapId][type] = new this.workerSourceTypes[type](this.actor, layers);
+
+            // use a wrapped actor so that we can attach a target mapId param
+            // to any messages invoked by the WorkerSource
+            var actor = {
+                send: function (type, data, callback, buffers) {
+                    this.actor.send(type, data, callback, buffers, mapId);
+                }.bind(this)
+            };
```
Comment (lucaswoj) [inline js/source/worker.js]: It feels like we're fighting our own architecture with this fake `Actor`. Can you think of a way to refactor & simplify? `Worker` and `Actor` are so tightly coupled it might make sense to merge them.

File: js/util/actor.js [hunk 2]
```diff
@@ -28,6 +28,12 @@ Actor.prototype.receive = function(message) {
         id = data.id,
         callback;
 
+    // if we're on the main thread handling a message from the worker, make
+    // sure that we only handle messages directed at this actor's the map
+    // instance
+    if (data.targetMapId && this.mapId !== data.targetMapId)
+        return;
```
Comment (lucaswoj) [inline js/util/actor.js]: Do you think there's a way you can make this code more self-documenting such that the comment is unnecessary?

File: js/util/actor.js [hunk 3]
```diff
@@ -55,10 +61,16 @@ Actor.prototype.receive = function(message) {
...
 };
 
-Actor.prototype.send = function(type, data, callback, buffers) {
+Actor.prototype.send = function(type, data, callback, buffers, targetMapId) {
     var id = callback ? this.mapId + ':' + this.callbackID++ : null;
     if (callback) this.callbacks[id] = callback;
-    this.postMessage({ mapId: this.mapId, type: type, id: String(id), data: data }, buffers);
+    this.postMessage({
+        targetMapId: targetMapId,
+        mapId: this.mapId,
```
Comment (lucaswoj) [inline js/util/actor.js]: Why do we need to transfer both `mapId` and a `targetMapId`? Doesn't [this guard](https://github.com/mapbox/mapbox-gl-js/pull/3133/files#diff-07866509a19229697416fd9d0d2cae10R34) ensure they are equal?

File: js/source/worker.js (hunk 1 above)
Comment (anandthakker) [inline js/source/worker.js]: I think merging Worker and Actor is probably beyond the scope of this bug fix, but I certainly agree your broader point over in #3034.

I was trying to keep the scope of this change as limited as possible, but maybe one way to simplify this a bit would be to replace WorkerSource's (and WorkerTile#parse's) `actor: Actor` parameter with just a `send: (type, data, callback)=>void` parameter.

File: js/util/actor.js (hunk 3 above)
Comment (anandthakker) [inline js/util/actor.js]: There are really two different things here:
 - For messages initiated from the main thread, `mapId` identifies the _sending_ map instance, which is really for the purpose of enabling the worker to track state related to different instances.
 - For messages initiated from the worker, `targetMapId` identifies the _target_ map instance.

It's true that since these two properties are used in totally disjoint cases, we could simply use `mapId` for both.... but following along your point above re: making the code better self-documenting, I think it's a bit clearer not to overload the same property for two different needs (especially since they're similar, but subtly different)

File: js/util/actor.js (hunk 2 above)
Comment (anandthakker) [inline js/util/actor.js]: Yep. Will do

**Comment by jfirebaugh** [comment]
Another issue with #2952 is that it can leak WebWorker `message` event bindings: the binding added in the `Actor` constructor is never removed. It looks like if the last `Map` is `remove`d than the workers will get shut down, but as long as there is at least one `Map`, then all the `Actors` ever created will stay live.

Can you add a fix for that to this PR as well?

**Comment by jfirebaugh** [comment]
Another issue: the blob URLs that webworkify creates aren't revoked; if you repeatedly create and remove maps, so that the worker pool is drained and refilled, they leak.

**Comment by anandthakker** [comment]
> Another issue with #2952 is that it can leak WebWorker message event bindings: the binding added in the Actor constructor is never removed. It looks like if the last Map is removed than the workers will get shut down, but as long as there is at least one Map, then all the Actors ever created will stay live.

I think this predates 2952, but yep I can add a fix for this.

**Comment by anandthakker** [comment]
> I think this predates 2952

Ah, actually it probably _doesn't_ predate 2952, since it's probably a pretty safe assumption that, before the worker pool, the `message` listeners were being removed in `WebWorker#terminate`.   My mistake.

**Comment by anandthakker** [comment]
@jfirebaugh included fixes to dispose of event listeners and revoke object URLs.

@lucaswoj also tried to clarify the code in `Actor` to avoid the need for an inline comment; but at the same time, I thought it did make sense to include standard jsdoc for `Actor#send`.

**Comment by lucaswoj** [comment]
This is ready to 🚢. We need to fix this bug before the next release. I'm also keen on simplify our worker architecture 😄
