### PR TITLE
Fix querySourceFeatures returning bad results on zooms past maxZoom

### LINKED ISSUE #2868: Fix incorrect z coordinate on overzoomed tiles
**mapbox-gl-js version**: 0.21.0

When calling `querySourceFeatures` past the max zoom of the source layer, the tiles returned are not in the viewport. They have the `x` and `y` values from the max zoom of the source layer but the `z` value from the actual zoom level. My recreation relies on some private layers but you can also see the error in the tile boundary calculation (11/328/794 is correct, 11/164/397 has the correct x/y for zoom 10):

screen shot 2016-07-14 at 11 08 03 am

I believe the [`reparseOverscaled` ternary operator](https://github.com/mapbox/mapbox-gl-js/blob/de61bbfa21f070e7afbe4fd42e24e8e44e7e25f1/js/source/tile_pyramid.js#L151) is reversed in the `TilePyramid`; when swapping `z` and `actualZ` locally the problem was resolved. I can add a PR but not sure of a good test case

### LINKED ISSUE #3722: querySourceFeatures returns invalid feature coordinates on high zoom levels
If the map zoom level > 16 the features returned from map.querySourceFeatures have invalid geometry coordinates (negative or otherwise nonsense).

https://jsbin.com/sesafumovi/edit?html,console,output

Can be reproduced on current master branch.

### PR DESCRIPTION
**Pull request by mourner**
Fixes #2868. Fixes #3722. 

~~I also removed the `reparseOverscaled` source option because it doesn't seem useful — we always want to reparse overscaled tiles for correct layout values, and we don't need to worry about performance because parsing overscaled tiles is very fast anyway (there's only a few on the screen and they're small).~~

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] write tests for all new functionality
 - [x] ~~document any changes to public APIs~~
 - [x] ~~post benchmark scores~~
 - [x] manually test the debug page

### CODE REVIEW

File: src/geo/transform.js [hunk 1]
```diff
@@ -248,7 +246,7 @@ class Transform {
             this.pointCoordinate(new Point(this.width, this.height), z),
             this.pointCoordinate(new Point(0, this.height), z)
         ];
-        return tileCover(z, cornerCoords, options.reparseOverscaled ? actualZ : z, this._renderWorldCopies)
```
Comment (ansis) [inline src/geo/transform.js]: Does this work for raster sources past their max zoom level? I think the previous behaviour was that it used the existing tiles from the max zoom level. Does this end up creating new tiles?

**Comment by mourner** [comment]
I also noticed (after the PR) that #4990 inadvertently contains the same fix. Sorry for not noticing earlier @asheemmamoowala!

**Comment by ralphking** [comment]
I'm not sure that this fixes https://github.com/mapbox/mapbox-gl-js/issues/3722

it sets reparseOverscaled to true, which seemingly does the opposite
