### PR TITLE
MapEventData#isSourceLoaded fix

### LINKED ISSUE #3958: MapDataEvent#isSourceLoaded always returns false
Could this be because the `data` event (which triggers the `sourcedata` event) is fired immediately _before_ the `source.load` event changes [`SourceCache._sourceLoaded` to true](https://github.com/mapbox/mapbox-gl-js/blob/master/js/source/source_cache.js#L30) ?

I thought that was the case, but a quick gut check to switch the function calls didn't change the result. But still it might need to be addressed after we figure out 👇 .

I think the root cause is that [`isSourceLoaded`](https://github.com/mapbox/mapbox-gl-js/blob/master/js/style/style.js#L378) is set right when `addSource` is called via [`setEventedParent`](https://github.com/mapbox/mapbox-gl-js/blob/25950e634b97db8e8c4e6c465b14e386a534a193/js/util/evented.js#L120) so `sourceCache.loaded()` is invoked only once, not every time the event fires like I believe was the intended behavior ??

### PR DESCRIPTION
**Pull request by mollymerp**
Working on fixing evaluation of `MapEventData#isSourceLoaded`

Fixes #3958 

Questions:
We only fire a `data` event with `dataType: source` when the TileJSON is loaded, but `isSourceLoaded: true` only occurs after all the tiles in for the source in the current viewport are loaded, so for `dataType:source` `EventData#isSourceLoaded` is still never `true`. Should we fire another `data` event of type `source` when all tiles are loaded `isSourceLoaded` flips to `true` ?

cc @lucaswoj @anandthakker @lbud 

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [ ] write tests for all new functionality
 - [x] document any changes to public APIs
 - [ ] post benchmark scores
 - [x] manually test the debug page

### CODE REVIEW

File: src/util/evented.js [hunk 1]
```diff
@@ -71,9 +71,13 @@ class Evented {
      */
     fire(type, data) {
         if (this.listens(type)) {
-
             data = util.extend({}, data, {type: type, target: this});
 
+            // determine if source is loaded when event is fired
+            if (typeof data.isSourceLoaded === "function") {
+                data.isSourceLoaded = data.isSourceLoaded();
+            };
```
Comment (anandthakker) [inline src/util/evented.js]: An alternative to this approach might be to change the semantics of `Evented#setEventedParent()` so that, if the evented parent `data` parameter is a function, it is evaluated during `fire()` rather than during `setEventedParent()`.

On the surface, that seems preferable to me because it avoids the hardcoding here... but it would require a review of `setEventedParent` to make sure we aren't counting on `data` being evaluated immediately anywhere else.

**Comment by mollymerp** [comment]
to keep the scope of this PR under control, I suggest we ship this fix as-in and I will handle a larger rejiggering of the source `data` event in a separate PR.

File: src/util/evented.js [hunk 2]
```diff
@@ -82,7 +81,7 @@ class Evented {
             }
 
             if (this._eventedParent) {
-                this._eventedParent.fire(type, util.extend({}, data, this._eventedParentData));
+                this._eventedParent.fire(type, util.extend({}, data, typeof this._eventedParentData === 'function' ? this._eventedParentData() : this._eventedParentData));
```
Comment (lucaswoj) [inline src/util/evented.js]: Could you add a test that ensures the `eventedParentData` function is called per emit and passes on the latest & greatest data?

Comment (lucaswoj) [inline src/util/evented.js]: Looks good otherwise 😄

Comment (mollymerp) [inline src/util/evented.js]: Great -- added a test!
