### PR TITLE
fix boxZoom bug

### LINKED ISSUE #2237: Disabling and enabling the box zoom interaction messes it up
Discovered this while working on #2173 

**mapbox-gl-js 0.15.0**:
### Steps to Trigger Behavior
1. Wait for the map to load <code>map.on("load", ...)</code>
2. Disable box zoom <code>map.boxZoom.disable();</code>
3. Enable box zoom <code>map.boxZoom.enable();</code>
4. Perform a box zoom

Demonstration at http://codepen.io/anon/pen/LNNqrP
### Expected Behavior

That it works as before disable/enable.
### Actual Behavior

Map gets stuck dragging right after the box zoom, as if the mouse button is down even though it is not.

This may be related to OSX and have a similar root cause of #1888

### PR DESCRIPTION
**Pull request by mollymerp**
fix #2237 where disabling then re-enabling the boxZoomHandler would result in a bug where the drag handler would be erroneously active after a boxZoom triggered `mouseup` event

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [ ] write tests for all new functionality
 - [x] document any changes to public APIs
 - [ ] post benchmark scores
 - [x] manually test the debug page

### CODE REVIEW

File: src/ui/handler/drag_pan.js [hunk 1]
```diff
@@ -190,6 +190,10 @@ class DragPanHandler {
     _ignoreEvent(e) {
         const map = this._map;
 
+        // if boxZoom is disabled and then re-enabled, the drag_pan event listener for mousedown will fire before
+        // the boxZoom event listener, so map.boxZoom.isActive() will return false resulting in an erroneous
+        // drag on mousemove once the boxZoom is released, so we need this additional check.
+        if (map.boxZoom && e.shiftKey && e.button === 0) return true;
```
Comment (anandthakker) [inline src/ui/handler/drag_pan.js]: Should this check also include `max.boxZoom.isActive()`?

Comment (mollymerp) [inline src/ui/handler/drag_pan.js]: the reason for this check is because `map.boxZoom.isActive()` returns `false` if BoxZoomHandler is disabled / re-enabled, so, no 🙃

Comment (mollymerp) [inline src/ui/handler/drag_pan.js]: I think I need to re-word this comment to make that more clear. its due to the firing order of event listeners attached to the `keydown` event.

Comment (anandthakker) [inline src/ui/handler/drag_pan.js]: Oh dear 🤦‍♂️.  I swear I really did read that comment , but then got turned upside-down thinking about event logic...

What made me ask was thinking about something like:
 - mousdown: start dragpan
 - press (and hold) shift
 - mouseup: i think the expectation would be to stop panning, but this check would  prevent that from happening (if I'm reading it right?)

Comment (mollymerp) [inline src/ui/handler/drag_pan.js]: you're right this is no bueno! thanks for catching. I'll rethink how to handle this 💭

**Comment by mollymerp** [comment]
Yep! Thanks @mourner
