### PR TITLE
Fix invalid LngLat with no currently loaded DEM tiles

### LINKED ISSUE #10610: getBounds() is returning Invalid LngLat object when terrain is enabled and map is at high zooms or large tilt.
I can only seem to replicate this on Mobile devices.
If I disable terrain mode getBounds() returns correctly.

https://github.com/mapbox/mapbox-gl-js/blob/798d073c5027e7b0d68a59bed733f4bfe0a2b43c/src/geo/transform.js#L1009

### PR DESCRIPTION
**Pull request by SnailBones**
## Launch Checklist
Closes #10610

When terrain is enabled and the map is quickly zoomed, `map.elevation.visibleDemTiles` occasionally returns an empty array while awaiting DEM tile loading. This previously caused `getBounds` to return null values,  As explained [here](https://github.com/mapbox/mapbox-gl-js/issues/10610#issuecomment-985742211) by @ted-piotrowski:

>  If `elevation.visibleDemTiles` is empty array and `elevation.exaggeration()` > 1 then `minmax.min * elevation.exaggeration()` will equal `Infinity`, possibly producing a `NaN` down the line:

This PR adds a fix by defaulting to the 2D `getBounds` behavior if no terrain is available.

This leaves undefined behavior in the application, where `getBounds` returns different results depending on whether terrain is loaded or not. It's also likely that if 1+ but not all DEM tiles are loaded, the bounds returned could be insufficient to completely cover all terrain, though this did not nor will they now throw an error.

I suspect that these cases are subtle enough to be only a minor issue. If we decide to address this in the future, we should consider the performance cost of delaying `getBounds`calls until terrain is loaded.

 - [x] briefly describe the changes in this PR
 - [x] write tests for all new functionality
 - [x] manually test the debug page
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [x] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog>Fixed 'getBounds' sometimes returning invalid LngLat when zooming on a map with terrain.</changelog>`

### CODE REVIEW

File: src/geo/transform.js [hunk 1]
```diff
@@ -1269,6 +1269,7 @@ class Transform {
     }
 
     _getBounds(min: number, max: number) {
+        assert(min < Number.MAX_VALUE);
```
Comment (karimnaaji) [inline src/geo/transform.js:1272]: nit: Should we leave this assert or is it somewhat redundant to [this one](https://github.com/mapbox/mapbox-gl-js/pull/11339/files#diff-a2b3330768267b8c7996b8bf292fcd864e8b768f538436813b0d7e19f7202176R1314)? It seems to cover the same, when we basically fail to retrieve the `minmax` from the DEMs.

File: src/geo/transform.js [hunk 2]
```diff
@@ -1301,6 +1302,7 @@ class Transform {
     _getBounds3D(): LngLatBounds {
         assert(this.elevation);
         const elevation = ((this.elevation: any): Elevation);
+        if (!elevation.visibleDemTiles.length) { return this._getBounds(0, 0); }
```
Comment (karimnaaji) [inline src/geo/transform.js:1305]: Good catch :+1:

**Review by karimnaaji — APPROVED** [review]
One nit but looks good to me otherwise.

File: src/geo/transform.js (hunk 1 above)
Comment (SnailBones) [reply src/geo/transform.js:1272]: Good point Karim! My intention was to protect against potential changes or additions to this code in the future, since the new unit test would rely on these assertions to catch a regression. But considering that this is a private function, I think we can safely consider this redundant.
