### PR TITLE
fix: update ImageAtlas render callbacks after image removal

### LINKED ISSUE #11558: removeImage on an animated image throws Uncaught TypeError: Cannot destructure property 'userImage' of 'e' as it is undefined
**mapbox-gl-js version**: 2.7.0

**browser**: Chrome

### Steps to Trigger Behavior

 1. Follow the example at https://docs.mapbox.com/mapbox-gl-js/example/add-image-animated/ to add an animated image to the map
 2. use `map.removeImage`

### Link to Demonstration

https://codepen.io/andrewharvey/pen/BamGabP

### Expected Behavior

no error, the image just gets removed.

### Actual Behavior

an error is logged in the console
```
Uncaught TypeError: Cannot destructure property 'userImage' of 'e' as it is undefined.
    at _ (style_image.js:34:12)
    at dispatchRenderCallbacks (image_manager.js:298:29)
    at jc.patchUpdatedImages (image_atlas.js:125:22)
    at ad.prepare (tile.js:384:29)
    at qp.prepare (source_cache.js:168:18)
    at _o.render (painter.js:484:29)
    at Map._render (map.js:2944:26)
    at map.js:3270:26
````

### PR DESCRIPTION
**Pull request by stepankuzmin**
`ImageAtlas` may still have render callbacks after removing the image in `ImageManager`.

Closes #11558

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] manually test the debug page
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [x] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog>fix: properly handle animated images render callbacks removal</changelog>`

### CODE REVIEW

File: src/render/image_atlas.js [hunk 1]
```diff
@@ -123,6 +123,7 @@ export default class ImageAtlas {
     }
 
     patchUpdatedImages(imageManager: ImageManager, texture: Texture) {
+        this.haveRenderCallbacks = this.haveRenderCallbacks.filter(id => imageManager.hasImage(id));
```
Comment (ryanhamley) [inline src/render/image_atlas.js:126]: Instead of filtering, could `dispatchRenderCallbacks` check that the image still exists before proceeding?

Comment (stepankuzmin) [reply src/render/image_atlas.js:126]: We can do that, but the image reference would persist in `haveRenderCallbacks` in `ImageAtlas`, and we continue to call `dispatchRenderCallbacks`.

We can mutate the `haveRenderCallbacks` reference in `dispatchRenderCallbacks`, but I think that it may lead to race conditions.

```js
imageManager.dispatchRenderCallbacks(this.haveRenderCallbacks);
```

**Review by ryanhamley — APPROVED** [review]
