### PR TITLE
error if invalid 'before' argument is passed to Map#addLayer

### LINKED ISSUE #3868: Unexpected behaviour when calling "Map#addLayer" with invalid "before" argument
I am using the Mapbox GL [example](https://www.mapbox.com/mapbox-gl-js/example/setstyle/) change a map's style.

When the style is switched to `dark-v9`, `basic-v9`, or `streets-v9`, existing layers reload with the `map.on('style.load', function () {}`  This is expected. 

However, this is not the case with `satellite-v9` - when the satellite style is toggled, the existing layers load behind the style.  Please see my example [code](http://iskandarblue.github.io/mapbox/code/test_parcels.html)

This is unexpected behavior.  Why does this happen and Is there a workaround?

### PR DESCRIPTION
**Pull request by mollymerp**
fix #3868

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] write tests for all new functionality
 - [x] document any changes to public APIs
 - [ ] post benchmark scores
 - [x] manually test the debug page

### CODE REVIEW

File: src/style/style.js [hunk 1]
```diff
@@ -568,7 +568,10 @@ class Style extends Evented {
 
         layer.setEventedParent(this, {layer: {id: id}});
 
-        const index = before ? this._order.indexOf(before) : this._order.length;
+        const beforeIndex = before ? this._order.indexOf(before) : 0;
```
Comment (peterqliu) [inline src/style/style.js]: @mollymerp is `0` the top or bottom of the stack? Hitting `map.style._order` in my console, the first layer in the array is visually under all other layers on the map.

Comment (mollymerp) [reply src/style/style.js]: I suppose this is misleading – `beforeIndex` isn't actually used unless `before` exists so the `0` value never gets assigned to `index`. I made it 0 instead of `null` to appease flow but I could make this clearer.

File: src/style/style.js [hunk 2]
```diff
@@ -568,7 +568,11 @@ class Style extends Evented {
 
         layer.setEventedParent(this, {layer: {id: id}});
 
-        const index = before ? this._order.indexOf(before) : this._order.length;
+
+        const beforeIndex = before ? this._order.indexOf(before) : -1;
+        const index = before && beforeIndex !== -1 ? beforeIndex : this._order.length;
+        if (before && beforeIndex === -1) util.warnOnce(`Layer with id "${before}" does not exist on this map. Adding layer to the top of the stack.`);
```
Comment (jfirebaugh) [inline src/style/style.js]: Let's report this via `this.fire('error', ...)` for consistency with non-existent layer IDs in `moveLayer`, `removeLayer`, etc.

File: test/unit/style/style.test.js [hunk 3]
```diff
@@ -1006,6 +1006,28 @@ test('Style#addLayer', (t) => {
...
+            layers: [{
+                id: 'a',
+                type: 'background'
+            }, {
+                id: 'b',
+                type: 'background'
+            }]
+        }));
+        const layer = {id: 'c', type: 'background'};
+        t.stub(console, 'error');
```
Comment (jfirebaugh) [inline test/unit/style/style.test.js]: Bind a handler for the `error` event rather than stubbing `console.error` (see the subsequent test for example).

File: src/style/style.js [hunk 4]
```diff
@@ -568,7 +568,12 @@ class Style extends Evented {
 
         layer.setEventedParent(this, {layer: {id: id}});
 
-        const index = before ? this._order.indexOf(before) : this._order.length;
+
+        const beforeIndex = before ? this._order.indexOf(before) : -1;
+        const index = before && beforeIndex !== -1 ? beforeIndex : this._order.length;
+        if (before && beforeIndex === -1) this.fire('error', {
```
Comment (jfirebaugh) [inline src/style/style.js]: Instead of adding to the top of the stack, return early without making changes in the case of an error.

File: src/style/style.js [hunk 5]
```diff
@@ -568,7 +568,12 @@ class Style extends Evented {
 
         layer.setEventedParent(this, {layer: {id: id}});
 
-        const index = before ? this._order.indexOf(before) : this._order.length;
+
+        const beforeIndex = before ? this._order.indexOf(before) : -1;
```
Comment (jfirebaugh) [inline src/style/style.js]: `this._order.length` can never be `-1`, so the conditionals can be simplified:

```
const index = before ? this._order.indexOf(before) : this._order.length;
if (index === -1) {
    // error
}

this._order.splice(index, ...);
```

Comment (mollymerp) [reply src/style/style.js]: ah good point! I still had to use `if (before && index === -1)` for flow to allow me to  include `before` in the error message.
