### PR TITLE
Fix redundant title in Map Feedback attribution

### LINKED ISSUE #11324: Redundant title text on "Improve this map" link
**mapbox-gl-js version**: v2.6.1

**browser**: N/A

### Steps to Trigger Behavior

 1. Scan a page with the [Wave evaluation tool](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh)

On version 2.6.1 
The text is: Improve this map
The title is: Improve this map

On Version 2.3.1
The text is: Improve this map
The title is: Map feedback

**Why it matters to me**
In Greece to get into a government program for a website grant, your website must pass certain tests. One of which is the WAVE evaluation tool. I am planning on using MapBox for future projects. I would like to use the most up-to-date version. But I can't due to it not passing the test.

Information from WAVE

**Alerts**
Redundant title text

**What It Means**
Title attribute text is the same as text or alternative text.

**Why It Matters**
The title attribute value is used to provide advisory information. It typically appears when the user hovers the mouse over an element. The advisory information presented should not be identical to or very similar to the element text or alternative text.

**How to Fix It**
In most cases, the title attribute can be removed, otherwise modify it to provide advisory, but not redundant information. Note that the title text may or may not be read by a screen-reader and is typically inaccessible to sighted keyboard users.

### PR DESCRIPTION
**Pull request by avpeery**
Closes #11324. PR #11064 removed adding a title attribute to Map Feedback (which was overwriting the previous title attribute "improve this map" that comes from the vector tile source). This quick fix removes the title attribute for Map Feedback as aria-label is being used instead.

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] manually test the debug page
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [x] add an entry inside this element for inclusion in the mapbox-gl-js changelog: <changelog>Removes redundant title attribute from `Improve this Map` attribution element</changelog>

### CODE REVIEW

File: src/ui/control/attribution_control.js [hunk 1]
```diff
@@ -98,6 +98,7 @@ class AttributionControl {
     _setElementTitle(element: HTMLElement, title: string) {
         const str = this._map._getUIString(`AttributionControl.${title}`);
         element.setAttribute('aria-label', str);
+        if (element.hasAttribute('title')) element.removeAttribute('title');
```
Comment (ryanhamley) [inline src/ui/control/attribution_control.js:101]: nit: the `if` statement isn't strictly necessary

**Review by ryanhamley — APPROVED** [review]
