### PR TITLE
Fix drag handler corner cases

### LINKED ISSUE #6192: Stuck in drag mode
1. Press left mouse button
2. Press control key
3. Release left mouse button
4. Release control key
5. Move the mouse

Expected: map does not pan.
Actual: map is stuck in pan drag mode.

### LINKED ISSUE #6194: Left-button mouse click shouldn't end right-button drag rotate
1. Press right mouse button
2. Press left mouse button
3. Release left mouse button
4. Move the mouse

Expected: map rotates/pitches.
Actual: nothing.

### PR DESCRIPTION
**Pull request by jfirebaugh**
* Ensure drag gesture ends even if the control key is down on mouseup (fixes #6192)
* Left-button mouse click shouldn't end right-button drag rotate (fixes #6194)

### CODE REVIEW

File: src/ui/handler/drag_pan.js [hunk 1]
```diff
@@ -89,13 +89,16 @@ class DragPanHandler {
...
+        if (this._map.boxZoom.isActive()) return;
+        if (this._map.dragRotate.isActive()) return;
         if (this.isActive()) return;
 
         if (e.touches) {
+            if ((e.touches: any).length > 1) return;
             window.document.addEventListener('touchmove', this._onMove);
             window.document.addEventListener('touchend', this._onUp);
         } else {
+            if (e.ctrlKey || e.button !== 0) return;
```
Comment (anandthakker) [inline src/ui/handler/drag_pan.js]: is `e.button` guaranteed to be defined in this case?  (Asking because in `_ignoreEvent`, we checked `e.button && e.button !== 0`.)
