### PR TITLE
Fix #12450 

### LINKED ISSUE #12450: Infinite loop in zoomFromMercatorZAdjusted
**mapbox-gl-js version**: v2.11.1

**browser**: Firefox, but also happens on Webkit

### Steps to Trigger Behavior

I'm not entirely sure yet. I am still pinpointing exactly what I do that causes this, in a minimal way, but I know that it has nothing to do with the input to the map because without changing my map interactions at all, things work fine sometimes. I think it might happen if the map is not visible on the page until after page load?

What I do know is I'm calling `map.fitBounds()` that triggers it (see below).

I know that's not helpful, but I wanted to at least get this posted with the details I do currently have in case someone more familiar with the code might have a clue.

### Link to Demonstration

https://jsbin.com/lulodecebi/edit?html,js,output

~~Working on this; will update if I have further details. Unfortunately my screen recorder isn't working today (it records a video but nothing moves... sigh, Linux).~~

### Expected Behavior

The map should not have an infinite loop and the page should not freeze.

### Actual Behavior

Firefox shows "This page is slowing down Firefox" -- when I choose to debug, I see this call stack:

```
zoomFromMercatorZAdjusted (https://api.mapbox.com/mapbox-gl-js/v2.11.1/mapbox-gl.js#36)
_cameraForBoundsOnGlobe (https://api.mapbox.com/mapbox-gl-js/v2.11.1/mapbox-gl.js#36)
_cameraForBounds (https://api.mapbox.com/mapbox-gl-js/v2.11.1/mapbox-gl.js#36)
cameraForBounds (https://api.mapbox.com/mapbox-gl-js/v2.11.1/mapbox-gl.js#36)
fitBounds (https://api.mapbox.com/mapbox-gl-js/v2.11.1/mapbox-gl.js#36)
```

I'm calling the function `fitBounds()`. It works fine except in certain cases, and that's what I'm trying to isolate currently.

It's this code in transform.js:

```js
    zoomFromMercatorZAdjusted(z: number): number {
        const getZoom = (zoom) => {
            const d = this.getCameraToCenterDistance(this.projection, zoom);
            return this.scaleZoom(d / (z * this.tileSize));
        };

        let zoom = getZoom(this.zoom);
        let diff = Math.abs(zoom - getZoom(zoom));
        let lastdiff;
        while (lastdiff !== diff) {
            zoom = getZoom(zoom);
            lastdiff = diff;
            diff = Math.abs(zoom - getZoom(zoom));
        }

        return zoom;
    }
```

Stepping over repeatedly goes between the `while(...` and `zoom =` lines, never anything else.

The scopes pane reveals:

```
Function Body
​
<this>: {…}
diff: NaN
getZoom:t(t)
lastdiff: NaN
zoom: NaN
```

Inside `getZoom()`, `d` is NaN and `z` is `-2.3265482126335146e-17` (and `tileSize` is 512). Even if `d` WAS a number, this would almost be division by 0.

FWIW, these are the bounds I'm fitting:

```
_ne: Object { lng: -115.9398431, lat: 35.2138334 }
_sw: Object { lng: -115.9398431, lat: 35.2138334 }
```

(There's only 1 marker on the map in this case. Note that this usually works, so I'm still trying to isolate why it doesn't work sometimes.)

### PR DESCRIPTION
**Pull request by karimnaaji**
Fix https://github.com/mapbox/mapbox-gl-js/issues/12450: Infinite loop in zoomFromMercatorZAdjusted.

- Prevent NaN by gating invalid values from the callee
- Prevent infinite loop by using a binary search instead of the previous method more prone to floating point comparison issues
- Add regression tests and new test for this function

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] include before/after visuals or gifs if this PR includes visual changes
 - [x] write tests for all new functionality
 - [x] manually test the debug page
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [x] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog>Fix potential infinite loop when calling fitBounds with globe projection</changelog>`

### CODE REVIEW

File: src/geo/transform.js [hunk 1]
```diff
@@ -2059,19 +2065,38 @@ class Transform {
...
-            const d = this.getCameraToCenterDistance(this.projection, zoom);
-            return this.scaleZoom(d / (z * this.tileSize));
+    zoomFromMercatorZAdjusted(mercatorZ: number): number {
+        assert(this.projection.name === 'globe');
+
+        const zoomFromMercatorZ = (zoom, mercatorZ) => {
+            assert(mercatorZ !== 0);
+            const worldSize = this.tileSize * Math.pow(2, zoom);
+            const d = this.getCameraToCenterDistance(this.projection, zoom, worldSize);
+            return this.scaleZoom(d / (mercatorZ * this.tileSize));
```
Comment (mourner) [inline src/geo/transform.js:2075]: Nit: this function is only used in one place so there's no need to make a closure, should be fine inline.

**Review by mourner — APPROVED** [review]
Nice! Binary search 💪
